#+title: GNU Emacs configuration
#+author: Osama Ghourab
#+email: osamaghox@gmail.com
#+language: en
#+options: ':t toc:nil num:t author:t email:t
#+startup: content indent
#+macro: latest-export-date (eval (format-time-string "%F %T %z"))
#+macro: word-count (eval (count-words (point-min) (point-max)))




النصائح الأهم لي:

** use package for melpa
واذا ما حصلت البكج تستخدم
package-vc المدمج في emacs 

** الشرح بيكون حسب الاحتياجات زي اللعبة

-------------
مثلًا
if we need to write araibc in emacs we cant use emacs keymaps while in arabic layout so we need to make input mthod arabic with `C-\`
(setq default-input-method "arabic")

بعد ما كملنا اللغة بنشوف اننا محتاجين خط عربي لذلك سنتخدم ..... الخ
-------------




** اي وظيفة جديدة داخل emacs

ما نكتب اسمها

osama-emacs-test.el

نكتبها بدون emacs لاننا بالفعل داخل البرنامج

** maybe dont use vim keys instead we will use caps lock as ctrl key and leader keys like vim does

** ربما با نخلي اول شيء تثبيت البكجات

جميع البكجات يعمل لهن load قبل اعداداتهن علشان ما يصير زي 
غلط بترتيب البكجات لان بعض البكجات ملكملات لبعض وايضًا جميع البكجات بنركز نخليه
 dever and config and init in use package


** this is the best for refernce https://github.com/bbatsov/prelude

or https://github.com/larstvei/dot-emacs/blob/main/init.org

or read this to know basics `https://github.com/ashton314/emacs-bedrock/blob/main/`

** make more links in `org config` with uuid


** this best modeline like neovim

https://github.com/konrad1977/punch-line


** add to every defun or devar a explain text to be showing in which key

** set themes like ef or prot theme and prot modeline

** تعلم من ترتيب prot تبعه ال org config

** watch video again `advanced org litrate config in emacs` by prot

** add more web links to the packages or sources or tutorials


* The early initialisation of Emacs (=early-init.el=)

This is the first file that Emacs reads when starting up. It should contain code that does not depend on any package or the proportions of the Emacs frame. In general, this early initialisation file is meant to set up a few basic things before Emacs produces the initial frame by delegating to the init.el

** The =early-init.el= section to set PATH and system tools

#+begin_src emacs-lisp :tangle "early-init.el" :mkdirp yes
;; Detect system type and add appropriate paths
(let ((path-sep (if (eq system-type 'windows-nt) ";" ":")))

  ;; Android (Termux) settings
  (when (string-equal system-type "android")
    (setenv "PATH" (format "%s%s%s"
                           "/data/data/com.termux/files/usr/bin"
                           path-sep
                           (getenv "PATH")))
    (setenv "LD_LIBRARY_PATH" (format "%s:%s"
                                      "/data/data/com.termux/files/usr/lib"
                                      (getenv "LD_LIBRARY_PATH")))
    (push "/data/data/com.termux/files/usr/bin" exec-path))

  ;; Windows settings
  (when (eq system-type 'windows-nt)
    ;; Git
    (let ((tools-dir (expand-file-name "~/osama-emacs/emacs-data/tools/")))
      (add-to-list 'exec-path (concat tools-dir "git/cmd"))
      (setenv "PATH" (concat (expand-file-name (concat tools-dir "git/cmd/"))
                             path-sep
                             (getenv "PATH")))

      ;; fd (file search tool)
      (add-to-list 'exec-path (concat tools-dir "fd/"))

      ;; ripgrep
      (add-to-list 'exec-path (concat tools-dir "ripgrep/")))))
#+end_src

* The main initialisation of Emacs (=init.el=)

This is where I define the Lisp macros used in my setup and load all the invidiual modules.

** The =init.el= entry point

#+begin_src emacs-lisp :tangle "init.el" :mkdirp yes
(defvar osama-emacs-dir (expand-file-name "~/.emacs.d/")
  "The root dir of the Osama Emacs distribution.")

(defvar osama-emacs-modules-dir (expand-file-name "modules" osama-emacs-dir)
  "This directory houses all of the built-in Osama Emacs modules.")
#+end_src

** The =init.el= settings for packages (=package.el=)

The =package.el= is built into Emacs and is perfectly fine for my
use-case. We do not need to load it explicitly, as it will be called
by ~use-package~ when it needs it

#+begin_src emacs-lisp :tangle "init.el" :mkdirp yes
;; Prevent Emacs from loading packages before init
(setq package-enable-at-startup nil)

(require 'package)

;; Package repositories
(setq package-archives
      '(("melpa" . "https://melpa.org/packages/")
        ("org"   . "https://orgmode.org/elpa/")
        ("elpa"  . "https://elpa.gnu.org/packages/")))

(package-initialize)

;; Install use-package if not installed
(unless (package-installed-p 'use-package)
  (unless package-archive-contents
    (package-refresh-contents))
  (package-install 'use-package))

(require 'use-package)

;; Automatically install declared packages
(setq use-package-always-ensure t)
#+end_src

This module load basic configurations that apply to most facets of Emacs.

* The modules of my Emacs configuration

In this module I define everything broadly related to the aesthetics of Emacs.

** The =osama-emacs-theme.el= module

*** The =osama-emacs-theme.el= section for ~theme~

#+begin_src emacs-lisp :tangle "modules/osama-emacs-theme.el" :mkdirp yes
(use-package doom-themes
  :init
  (load-theme 'doom-dracula t))
#+end_src

*** The =osama-emacs-theme.el= section for ~modeline~
#+begin_src emacs-lisp :tangle "modules/osama-emacs-theme.el" :mkdirp yes
(use-package doom-modeline
  :ensure t
  :init
  (doom-modeline-mode 1)
  :custom
  (doom-modeline-height 40)
  (doom-modeline-bar-width 3)
  (doom-modeline-buffer-file-name-style 'truncate-with-project)
  (doom-modeline-icon t)
  (doom-modeline-major-mode-icon t)
  (doom-modeline-minor-modes nil)
  (doom-modeline-enable-word-count t)
  (doom-modeline-indent-info t))
#+end_src

** The =osama-emacs-fonts.el= module


*** The =osama-emacs-fonts.el= section for ~nerd-icons~ fonts

#+begin_src emacs-lisp :tangle "modules/osama-emacs-fonts.el" :mkdirp yes
;; Define the folder to save fonts directly inside fonts
(defvar osama-icons-dir
  (expand-file-name "sync-thing/online-sync/emacs/emacs-data/fonts/"
                    (getenv "HOME"))
  "Custom directory to store icon fonts.")

;; Create the folder if it doesn't exist
(unless (file-directory-p osama-icons-dir)
  (make-directory osama-icons-dir t))

;; Helper function to download a font if missing
(defun osama-download-font-if-missing (font-name url)
  "Download FONT-NAME from URL to `osama-icons-dir` if missing."
  (let ((target (expand-file-name font-name osama-emacs-icons-dir)))
    (unless (file-exists-p target)
      (url-copy-file url target t)
      (message "Downloaded: %s" font-name))))

;; Download all-the-icons fonts
(use-package all-the-icons
  :config
  (dolist (font
           '(("all-the-icons.ttf" . "https://github.com/domtronn/all-the-icons.el/raw/master/fonts/all-the-icons.ttf")
             ("file-icons.ttf" . "https://github.com/domtronn/all-the-icons.el/raw/master/fonts/file-icons.ttf")
             ("material-design-icons.ttf" . "https://github.com/domtronn/all-the-icons.el/raw/master/fonts/material-design-icons.ttf")
             ("octicons.ttf" . "https://github.com/domtronn/all-the-icons.el/raw/master/fonts/octicons.ttf")
             ("weathericons.ttf" . "https://github.com/domtronn/all-the-icons.el/raw/master/fonts/weathericons.ttf")
             ("fontawesome.ttf" . "https://github.com/domtronn/all-the-icons.el/raw/master/fonts/fontawesome.ttf"))))
    (osama-download-font-if-missing (car font) (cdr font))))

;; Download nerd-icons fonts (including NFM.ttf)
(use-package nerd-icons
  :config
  (dolist (font
           '(("NerdFontsSymbolsOnly.ttf" . "https://github.com/rainstormstudio/nerd-icons.el/raw/main/fonts/NerdFontsSymbolsOnly.ttf")
             ("NFM.ttf" . "https://github.com/rainstormstudio/nerd-icons.el/raw/main/fonts/NFM.ttf"))))
    (osama-download-font-if-missing (car font) (cdr font))))
#+end_src

*** The =osama-emacs-fonts.el=: Section for Font Customization

#+begin_src emacs-lisp :tangle "modules/osama-emacs-fonts.el" :mkdirp yes
(use-package fontaine
  :ensure t
  :hook (after-init . (lambda ()
                        (fontaine-mode 1)
                        (fontaine-set-preset 'osama-fonts)))
  :config
  ;; Define your custom preset
  (setq fontaine-presets
        '((osama-fonts
           :default-family "Montserrat"
           :default-weight regular
           :default-height 120
           :variable-pitch-family "Montserrat"
           :variable-pitch-height 1.2
           :fixed-pitch-family "Fira Code"
           :fixed-pitch-height 120
           :unicode-family "STC Forward"
           :unicode-height 120))))

;; Create fonts directory if it doesn't exist
(defvar osama-fonts-dir (expand-file-name "~/osama-emacs/emacs-data/fonts/")
  "Directory to store fonts for Emacs.")

(unless (file-directory-p osama-fonts-dir)
  (make-directory osama-fonts-dir t))
#+end_src

** The =osama-emacs-essentials.el= module

This module load basic configurations that apply to most facets of Emacs. Many of my own custom libraries are loaded here 

*** The =osama-emacs-essentials.el= Section for Hide Tool bar

#+begin_src emacs-lisp :tangle "modules/osama-emacs-essentials.el" :mkdirp yes
(scroll-bar-mode -1)        ; Disable visible scrollbar
(tool-bar-mode -1)          ; Disable the toolbar
(tooltip-mode -1)           ; Disable tooltips
(set-fringe-mode 10)        ; Give some breathing room
(menu-bar-mode -1)          ; Disable the menu bar
#+end_src

*** The =osama-emacs-essentials.el= Section for UI Basics

#+begin_src emacs-lisp :tangle "modules/osama-emacs-essentials.el" :mkdirp yes
;; Visible bell
(setq visible-bell t)

;; Show current column number
(column-number-mode)

;; Enable line numbers globally and disable in specific modes
(global-display-line-numbers-mode t)
(dolist (mode '(org-mode-hook
                term-mode-hook
                shell-mode-hook
                eshell-mode-hook))
  (add-hook mode (lambda () (display-line-numbers-mode 0))))

;; Make cursor a vertical bar
(setq-default cursor-type 'bar)

;; Highlight current line
(global-hl-line-mode 1)
#+end_src

*** The =osama-emacs-essentials.el= Section for Session, Auto-Save & Backup Management

#+begin_src emacs-lisp :tangle "modules/osama-emacs-essentials.el" :mkdirp yes
;; Define cache directory
(defvar osama-cache-dir
  (expand-file-name "~/osama-emacs/emacs-cache/")
  "Portable directory for saving Emacs session cache across devices.")

;; Ensure cache directory exists
(defun osama-ensure-cache-directory (dir)
  "Ensure that the cache directory DIR exists, creating it if necessary."
  (unless (file-directory-p dir)
    (make-directory dir t)))

;; Prepare subdirectories
(let ((dirs '("savehist" "recentf" "desktop" "backups" "autosaves")))
  (dolist (sub dirs)
    (osama-ensure-cache-directory (expand-file-name sub osama-cache-dir))))

;; Savehist: command history
(setq savehist-file (expand-file-name "savehist/savehist" osama-cache-dir))
(savehist-mode 1)

;; Recentf: recent files list
(setq recentf-save-file (expand-file-name "recentf/recentf" osama-cache-dir))
(recentf-mode 1)

;; Desktop: full session restore
(setq desktop-path           (list (expand-file-name "desktop" osama-cache-dir))
      desktop-dirname        (expand-file-name "desktop" osama-cache-dir)
      desktop-base-file-name "emacs-desktop")
(desktop-save-mode 1)

;; Backups: store ~ files in backups/
(setq backup-directory-alist
      `((".*" . ,(expand-file-name "backups/" osama-cache-dir)))
      backup-by-copying t
      version-control t
      delete-old-versions t
      kept-new-versions 5
      kept-old-versions 2)

;; Auto-saves: store #files# in autosaves/
(setq auto-save-file-name-transforms
      `((".*" ,(concat (expand-file-name "autosaves/" osama-cache-dir) "\\1") t))
      auto-save-default t
      auto-save-timeout 20
      auto-save-interval 200)

;; Optional: disable lockfiles
(setq create-lockfiles nil)
#+end_src

*** The =osama-emacs-essentials.el= Settings for Better Performance

#+begin_src emacs-lisp :tangle "modules/osama-emacs-essentials.el" :mkdirp yes
;; Increase GC threshold during startup to speed up launch
  (setq gc-cons-threshold (* 50 1000 1000))
  (add-hook 'emacs-startup-hook
            (lambda () (setq gc-cons-threshold (* 2 1000 1000))))
#+end_src

*** The =osama-emacs-essentials.el= Section for Support Arabic Filenames

#+begin_src emacs-lisp :tangle "modules/osama-emacs-essentials.el" :mkdirp yes
  (prefer-coding-system 'utf-8)
  (setq default-buffer-file-coding-system 'utf-8)
#+end_src

*** The =osama-emacs-essentials.el= Section for Paragraph Text Direction

#+begin_src emacs-lisp :tangle "modules/osama-emacs-essentials.el" :mkdirp yes
;; Enable text reordering for right-to-left (RTL) languages
(setq-default bidi-display-reordering t)

;; Default mode for all files (paragraph direction is automatic)
(setq-default bidi-paragraph-direction nil)

(defun osama-emacs-toggle-bidi-paragraph-direction ()
  "Toggle paragraph direction between LTR, RTL, and Auto in any Emacs mode."
  (interactive)
  (setq bidi-paragraph-direction
        (cond
         ((eq bidi-paragraph-direction nil) 'left-to-right)
         ((eq bidi-paragraph-direction 'left-to-right) 'right-to-left)
         ((eq bidi-paragraph-direction 'right-to-left) nil)))
  (message "Paragraph direction now: %s"
           (pcase bidi-paragraph-direction
             ('left-to-right "LTR")
             ('right-to-left "RTL")
             (_ "Auto")))

  (recenter))

;; Set a global shortcut to toggle paragraph direction in all Emacs modes
(global-set-key (kbd "C-c r") #'osama-emacs-toggle-bidi-paragraph-direction)
#+end_src

*** The =osama-emacs-essentials.el= Section for 

** The =osama-emacs-completion.el= module

The term “completion” describes a process where user input is assisted by pattern matching algorithms to type out incomplete terms. The most basic way of this model of interaction is what we get in a command-line prompt, where we can hit TAB to expand the word before point to something the program already knows about (e.g ema followed by TAB may complete to emacs).

In Emacs, completion encompasses user interfaces that show the available candidates (the likely options) right away, as well as provide more advanced capabilities for storing the history of previous inputs, displaying helpful annotations next to each candidate, and “completion styles” to control how user input is matched to candidates. Because we use the minibuffer for most common interactions, completion is an integral part of any setup.

*** The =osama-emacs-completion.el= section for ~which-key~

The which-key package provides hints for keys that complete the currently incomplete sequence.

#+begin_src emacs-lisp :tangle "modules/osama-emacs-completion.el" :mkdirp yes
(use-package which-key
  :init (which-key-mode)
  :diminish which-key-mode
  :config
  (setq which-key-idle-delay 1))
#+end_src

*** The =osama-emacs-completion.el= section for ~vertico~

The ~vertico~ package by Daniel Mendler displays the minibuffer in a vertical layout. Under the hood, it takes care to be responsive and to handle even massive completion tables gracefully. Whereas, say, the built-in completion user interface will suffer from a noticeable performance penalty.

#+begin_src emacs-lisp :tangle "modules/osama-emacs-completion.el" :mkdirp yes
(use-package vertico
  :ensure t
  :config
  (setq vertico-cycle t
        vertico-resize nil)
  (vertico-mode 1))
#+end_src

*** The =osama-emacs-completion.el= section for ~marginalia~

The ~marginalia~ package, co-authored by Daniel Mendler and Omar Antolín Camarena, provides helpful annotations to the side of completion candidates. We see its effect, for example, when we call M-x: each command has a brief description next to it (taken from its doc string) as well as a key binding, if it has one.

#+begin_src emacs-lisp :tangle "modules/osama-emacs-completion.el" :mkdirp yes
(use-package marginalia
  :after vertico
  :init
  (marginalia-mode))
#+end_src

*** The =osama-emacs-completion.el= section for ~consult~

~consult~ is another wonderful package by Daniel Mendler. It provides a number of commands that turbocharge the minibuffer with advanced capabilities for filtering, asynchronous input, and previewing of the current candidate’s context.

#+begin_src emacs-lisp :tangle "modules/osama-emacs-completion.el" :mkdirp yes
(use-package consult
  :bind (("C-s" . consult-line)
         ("C-x b" . consult-buffer)
         ("C-M-j" . consult-switch-buffer)
         ("M-y" . consult-yank-pop)))
#+end_src





*** The =osama-emacs-completion.el= section for ~orderless~

~orderless~ is a completion style that matches input out-of-order. For example, in pa can match both insert-pair and package-install. Components are space-separated by default. Its design is powerful but avoids many false positives.

#+begin_src emacs-lisp :tangle "modules/osama-emacs-completion.el" :mkdirp yes
(use-package orderless
  :custom
  (completion-styles '(orderless))
  (completion-category-defaults nil))
#+end_src

*** The =osama-emacs-completion.el= section for ~embark~

~embark~ by Omar Antolín Camarena lets you perform context-specific actions via keybindings. embark-act shows a list of actions for the current context (e.g., describe a symbol, manipulate files), while embark-dwim performs the default action. It can also collect minibuffer candidates into a buffer for further operations like in dired or ibuffer.

#+begin_src emacs-lisp :tangle "modules/osama-emacs-completion.el" :mkdirp yes
(use-package embark
  :bind (("C-." . embark-act)
         ("C-;" . embark-dwim))
  :init
  (setq embark-prompter 'embark-completing-read-prompter))
#+end_src

*** The =osama-emacs-completion.el= section for ~corfu~

Corfu enhances in-buffer completion with a small completion popup. The current candidates are shown in a popup below or above the point, and can be selected by moving up and down. Corfu is the minimalistic in-buffer completion counterpart of the Vertico minibuffer UI.

#+begin_src emacs-lisp :tangle "modules/osama-emacs-completion.el" :mkdirp yes
(use-package corfu
  :ensure t
  :init
  (global-corfu-mode))
#+end_src

*** The =osama-emacs-completion.el= section for ~corfu~

Helpful is an alternative to the built-in Emacs help that provides much more contextual information.

#+begin_src emacs-lisp :tangle "modules/osama-emacs-completion.el" :mkdirp yes
(use-package helpful
  :bind
  ([remap describe-function] . helpful-function)
  ([remap describe-command]  . helpful-command)
  ([remap describe-variable] . helpful-variable)
  ([remap describe-key]      . helpful-key))
#+end_src

** The =osama-emacs-dired.el= module

** The =osama-emacs-windows.el= module

** The =osama-emacs-org.el= module

org modern + org appear

At its core, Org is a plain text markup language. By "markup
language", we refer to the use of common characters to apply styling,
such as how a word wrapped in asterisks acquires strong emphasis.
Check the video I link to above on the basics of Org mode.

Though what makes Org powerful is not the markup per se, but the fact
that it has a rich corpus of Emacs Lisp code that does a lot with this
otherwise plain text notation. Some of the headline features:

- Cycle the visibility of any heading and its subheadings. This lets
  you quickly fold a section you do not need to see (or reveal the one
  you care about).
- Mix prose with code in a single document to either make the whole
  thing an actual program or to evaluate/demonstrate some snippets.
- Convert ("export") an Org file to a variety of formats, including
  HTML and PDF.
- Use LaTeX inside of Org files to produce a scientific paper without
  all the markup of LaTeX.
- Manage TODO lists and implement a concomitant methodology of
  labelling task states.
- Quickly shift a "thing" (heading, list item, paragraph, ...) further
  up or down in the file.
- Use tables with formulas as a lightweight alternative to spreadsheet
  software.
- Capture data or fleeting thoughts efficiently using templates.
- Maintain an agenda for all your date-bound activities.
- Clock in and out of tasks, to eventually track how you are spending
  your time.
- Link to files regardless of file type. This includes special links
  such as to an Info manual or an email.

In other words, Org is highly capable and widely considered one of the
killer apps of Emacs.

This section covers the relevant configurations. You will notice that
it is not limited to Org, as some other built-in features are also
relevant here.

*** The =osama-emacs-org.el= section for the ~calendar~

The calendar is technically independent of Org, though it tightly integrates with it.
We can see this when setting timestamps, such as when defining a SCHEDULED or DEADLINE entry for a given heading.
Here, I am simply setting some stylistic preferences.

#+begin_src emacs-lisp :tangle "modules/osama-emacs-org.el" :mkdirp yes
;;; Calendar setup
(use-package calendar
  :ensure nil ;; calendar is built into Emacs
  :commands (calendar)
  :config
  ;; Do not highlight diary entries in the calendar
  (setq calendar-mark-diary-entries-flag nil)

  ;; Show holidays
  (setq calendar-mark-holidays-flag t)

  ;; Do not display a dedicated calendar mode line
  (setq calendar-mode-line-format nil)

  ;; Time format (24-hour)
  (setq calendar-time-display-form
        '(24-hours ":" minutes
          (when time-zone (format "(%s)" time-zone))))

  ;; Start the week on Monday instead of Sunday
  (setq calendar-week-start-day 1)

  ;; Display dates in ISO format (example: 2025-08-18)
  (setq calendar-date-style 'iso)

  ;; Show numeric time zone
  (setq calendar-time-zone-style 'numeric)

  ;; Coordinates (for sunrise/sunset calculation)
  ;; Change them according to your city
  (setq calendar-latitude 15.3694    ; Sana'a (example)
        calendar-longitude 44.1910)

  ;; Time zone
  (setq calendar-standard-time-zone-name "+0300") ; GMT+3
  (setq calendar-daylight-time-zone-name "+0300"))
#+end_src

*** The =osama-emacs-org.el= section about appointment reminders (=appt.el=)

The built-in appt.el handles appointment notifications. It was originally designed for the diary but also integrates well with the Org agenda. I extend this integration so that whenever I add or change a task, the appointments are refreshed through hooks and advice.
Here I only keep minimal settings: I don’t need full agenda details, just a mode line notice showing how many minutes remain until the event.
In Org files, each heading can have an APPT_WARNTIME property (minutes before the event). I use this with org-capture for time-sensitive tasks like coaching sessions.

#+begin_src emacs-lisp :tangle "modules/osama-emacs-org.el" :mkdirp yes
(use-package appt
  :ensure nil ;; built-in in Emacs, no need to install
  :commands (appt-activate) ;; main command to activate the system
  :config
  (setq appt-display-diary nil          ;; do not use the old diary
        appt-display-format nil         ;; default display format
        appt-display-mode-line t        ;; show reminder in the mode line
        appt-display-interval 3         ;; repeat reminder every 3 minutes
        appt-audible nil                ;; sound disabled (set to t for sound)
        appt-warning-time-regexp "appt \\([0-9]+\\)" ;; regex for diary
        appt-message-warning-time 6)    ;; warn 6 minutes before

  (with-eval-after-load 'org-agenda
    (appt-activate 1) ;; enable appt with org-agenda

    ;; convert Org tasks with time info into appt reminders
    (org-agenda-to-appt)))
#+end_src


*** The =osama-emacs-org.el= section with basic Org settings

Org, also known as "Org mode", is one of the potentially most useful
feature sets available to every Emacs user. At its core, Org is a
lightweight markup language: you can have headings and paragraphs,
mark a portion of text with emphasis, produce bullet lists, include
code blocks, and the like. Though what really sets Org apart from
other markup languages is the rich corpus of Emacs Lisp written around
it to do all sorts of tasks with this otherwise plain text format.

With Org you can write technical documents (e.g. the manuals of all my
Emacs packages), maintain a simple or highly sophisticated system for
task management, organise your life using the agenda, write tables
that can evaluate formulas to have spreadsheet functionality, have
embedded LaTeX, evaluate code blocks in a wide range of programming
languages and reuse their results for literate programming, include
the contents of other files into a singular file, use one file to
generate other files/directories with all their contents, and export
the Org document to a variety of formats like =.pdf= and =.odt=.
Furthermore, Org can be used as a lightweight, plain text database, as
each heading can have its own metadata. This has practical
applications in most of the aforementioned.

In short, if something can be done with plain text, Org probably does
it already or has all the elements for piecing it together.

This being Emacs, everything is customisable and Org is a good example
of this. There are a lot of user options for us to tweak things to our
liking. I do as much, though know that Org is perfectly usable without
any configuration. The following sections contain further commentary
on how I use Org.

#+begin_src emacs-lisp :tangle "modules/osama-emacs-org.el" :mkdirp yes
;;; Org-mode (basic personal setup)
(use-package org
  :ensure nil ;; org is built-in
  :init
  ;; Org files directory
  (setq org-directory (expand-file-name "~/Documents/org/"))
  ;; Depth for imenu
  (setq org-imenu-depth 5)
  :bind
  ( :map global-map
    ("C-c l" . org-store-link)
    ("C-c o" . org-open-at-point-global))
  :config
  ;; Fold indicator
  (setq org-ellipsis "⮧")
  ;; Basic appearance options
  (setq org-hide-emphasis-markers t) ; hide *bold* / /italic/ markers
  (setq org-hide-leading-stars t)    ; hide extra stars in headings
  (setq org-return-follows-link t)   ; RET follows links
  (setq org-cycle-separator-lines 0) ; no empty line between folds
  (setq org-insert-heading-respect-content t) ; respect content when inserting heading
  (setq org-fontify-quote-and-verse-blocks t) ; highlight quote/verse
  (setq org-fontify-whole-block-delimiter-line t)) ; color entire block delimiter line
#+end_src






** The =osama-emacs-system-custom= module

*** The =osama-emacs-android-custom= module

*** The =osama-emacs-windows-custom= module

* Android Section For Personal Settings

* The Personal Functions
