#+title: GNU Emacs configuration
#+author: Osama Ghourab
#+email: osamaghox@gmail.com
#+language: en
#+options: ':t toc:nil num:t author:t email:t
#+startup: content indent
#+macro: latest-export-date (eval (format-time-string "%F %T %z"))
#+macro: word-count (eval (count-words (point-min) (point-max)))

* The early initialisation of Emacs (early-init.el)

This is the first file that Emacs reads when starting up. It should contain code that does not depend on any package or the proportions of the Emacs frame. In general, this early initialisation file is meant to set up a few basic things before Emacs produces the initial frame by delegating to the init.el

** The =early-init.el= section to set PATH and system tools

#+begin_src emacs-lisp :tangle "early-init.el" :mkdirp yes
;; Detect system type and add appropriate paths
(let ((path-sep (if (eq system-type 'windows-nt) ";" ":")))

  ;; Android (Termux) settings
  (when (string-equal system-type "android")
    (setenv "PATH" (format "%s%s%s"
                           "/data/data/com.termux/files/usr/bin"
                           path-sep
                           (getenv "PATH")))
    (setenv "LD_LIBRARY_PATH" (format "%s:%s"
                                      "/data/data/com.termux/files/usr/lib"
                                      (getenv "LD_LIBRARY_PATH")))
    (push "/data/data/com.termux/files/usr/bin" exec-path))

  ;; Windows settings
  (when (eq system-type 'windows-nt)
    ;; Git
    (add-to-list 'exec-path "~/sync-thing/online-sync/emacs/emacs-data/tools/git/cmd")
    (setenv "PATH" (concat (expand-file-name "~/sync-thing/online-sync/emacs/emacs-data/tools/git/cmd/")
                           path-sep
                           (getenv "PATH")))

    ;; fd (file search tool)
    (add-to-list 'exec-path "~/sync-thing/online-sync/emacs/emacs-data/tools/fd/")

    ;; ripgrep
    (add-to-list 'exec-path "~/sync-thing/online-sync/emacs/emacs-data/tools/ripgrep/")))
#+end_src

* The main initialisation of Emacs (init.el)

This is where I define the Lisp macros used in my setup and load all the invidiual modules.


** The =init.el= entry point

#+begin_src emacs-lisp :tangle "init.el" :mkdirp yes
(add-to-list 'load-path (expand-file-name "lisp" user-emacs-directory))

(require 'osama-emacs-core)
(require 'osama-emacs-packages)
(require 'osama-emacs-ui)
#+end_src


* The modules of my Emacs configuration

In this module I define everything broadly related to the aesthetics of Emacs.

** The =osama-emacs-core.el=

*** The =osama-emacs-packages.el= section for package management

#+begin_src emacs-lisp :tangle "init.el" :mkdirp yes
;;; osama-emacs-packages.el --- Package management -*- lexical-binding: t; -*-

;; Prevent Emacs from loading packages before init
(setq package-enable-at-startup nil)

(require 'package)

;; Package repositories
(setq package-archives
      '(("melpa" . "https://melpa.org/packages/")
        ("org"   . "https://orgmode.org/elpa/")
        ("elpa"  . "https://elpa.gnu.org/packages/")))

(package-initialize)

;; Install use-package if not installed
(unless (package-installed-p 'use-package)
  (unless package-archive-contents
    (package-refresh-contents))
  (package-install 'use-package))

(require 'use-package)

;; Automatically install declared packages
(setq use-package-always-ensure t)

(provide 'osama-emacs-packages)
;;; osama-emacs-packages.el ends here
#+end_src





