#+title: GNU Emacs configuration
#+author: Osama Ghourab
#+email: osamaghox@gmail.com
#+language: en
#+options: ':t toc:nil num:t author:t email:t
#+startup: content indent
#+macro: latest-export-date (eval (format-time-string "%F %T %z"))
#+macro: word-count (eval (count-words (point-min) (point-max)))

* ممنوع تستخدم الماوس والنم باد و arrows


* Prefix Keys

| Command     | Key |
|-------------+-----|
| help        | h   |
| text        | x   |
| search      | s   |
| windows     | w   |
| emacs       | e   |
| notes       | n   |
| org         | o   |
| org agenda      | o a |
| org capture      | o a |
| org clocking      | o a |
| org export      | o a |
| agenda      | o a |
| agenda      | o a |
| files       | f   |
| buffers     | b   |
| dired       | d   |
| toggles     | t   |
| insert      | i   |
| attachments | a   |


* Basic Keybindings

| M-x                                  | Description                                | Keybinding |
|--------------------------------------+-------------------------------------------+------------|
| describe-personal-keybindings        | Show all personal keybindings             |         |
|describe-keybindings                   |Show all current keybindings | C-h b
|global-unset-key    | Unbind a global keybinding| |



* Random things
-------------------------------- straight.el package manager ------------------------------
;; Bootstrap straight.el
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/radian-software/straight.el/develop/misc/bootstrap.el")
      (goto-char (point-min))
      (erase-buffer)
      (insert-buffer-substring)
      (write-file bootstrap-file)))
  (load bootstrap-file nil 'nomessage))

;; Configure use-package to use straight.el
(straight-use-package 'use-package)
(setq use-package-always-ensure t)


(use-package punch-line
  :straight (punch-line :host github :repo "konrad1977/punch-line")
  :config
  ;; هنا تضع أي إعدادات خاصة بالحزمة
  ;; (punch-line-mode 1)
  )
-------------------------------- straight.el package manager ------------------------------

** lazy loading use-packages

** use package for melpa
واذا ما حصلت البكج تستخدم
package-vc المدمج في emacs 

** الشرح بيكون حسب الاحتياجات زي اللعبة

-------------
مثلًا
if we need to write araibc in emacs we cant use emacs keymaps while in arabic layout so we need to make input mthod arabic with `C-\`
(setq default-input-method "arabic")

بعد ما كملنا اللغة بنشوف اننا محتاجين خط عربي لذلك سنتخدم ..... الخ
-------------

** اي وظيفة جديدة داخل emacs

ما نكتب اسمها

osama-emacs-test.el

نكتبها بدون emacs لاننا بالفعل داخل البرنامج

** maybe dont use vim keys instead we will use caps lock as ctrl key and leader keys like vim does

** ربما با نخلي اول شيء تثبيت البكجات

جميع البكجات يعمل لهن load قبل اعداداتهن علشان ما يصير زي 
غلط بترتيب البكجات لان بعض البكجات ملكملات لبعض وايضًا جميع البكجات بنركز نخليه
 dever and config and init in use package


** this is the best for refernce

https://github.com/rougier/dotemacs
https://github.com/SophieBosio/.emacs.d/blob/main/init.org#mode-line
https://github.com/ianyepan/yay-evil-emacs/blob/master/config.org
https://github.com/pprevos/emacs-writing-studio/blob/master/init.el

or read this to know basics `https://github.com/ashton314/emacs-bedrock/blob/main/`

** make more links in `org config` with uuid


** this best modeline like neovim

https://github.com/konrad1977/punch-line


** add to every defun or devar a explain text to be showing in which key

** set themes like ef or prot theme and prot modeline

** تعلم من ترتيب prot تبعه ال org config

** watch video again `advanced org litrate config in emacs` by prot

** add more web links to the packages or sources or tutorials


* The early initialisation of Emacs (=early-init.el=)

This is the first file that Emacs reads when starting up. It should contain code that does not depend on any package or the proportions of the Emacs frame. In general, this early initialisation file is meant to set up a few basic things before Emacs produces the initial frame by delegating to the init.el

** The =early-init.el= section to set PATH and system tools

#+begin_src emacs-lisp :tangle "early-init.el" :mkdirp yes
;; Detect system type and add appropriate paths
(let ((path-sep (if (eq system-type 'windows-nt) ";" ":")))

  ;; Android (Termux) settings
  (when (string-equal system-type "android")
    (setenv "PATH" (format "%s%s%s"
                           "/data/data/com.termux/files/usr/bin"
                           path-sep
                           (getenv "PATH")))
    (setenv "LD_LIBRARY_PATH" (format "%s:%s"
                                      "/data/data/com.termux/files/usr/lib"
                                      (getenv "LD_LIBRARY_PATH")))
    (push "/data/data/com.termux/files/usr/bin" exec-path))

  ;; Windows settings
  (when (eq system-type 'windows-nt)
    ;; Git
    (let ((tools-dir (expand-file-name "~/osama-emacs/emacs-data/tools/")))
      (add-to-list 'exec-path (concat tools-dir "git/cmd"))
      (setenv "PATH" (concat (expand-file-name (concat tools-dir "git/cmd/"))
                             path-sep
                             (getenv "PATH")))

      ;; fd (file search tool)
      (add-to-list 'exec-path (concat tools-dir "fd/"))

      ;; ripgrep
      (add-to-list 'exec-path (concat tools-dir "ripgrep/")))))
#+end_src

* The main initialisation of Emacs (=init.el=)

This is where I define the Lisp macros used in my setup and load all the invidiual modules.

** The =init.el= settings for packages (=package.el=)

The =package.el= is built into Emacs and is perfectly fine for my
use-case. We do not need to load it explicitly, as it will be called
by ~use-package~ when it needs it

#+begin_src emacs-lisp :tangle "init.el" :mkdirp yes
(require 'package)
(setq package-archives
      '(("melpa" . "https://melpa.org/packages/")
        ("org"   . "https://orgmode.org/elpa/")
        ("elpa"  . "https://elpa.gnu.org/packages/")))
(package-initialize)

;; Install use-package if missing
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))

(require 'use-package)
(setq use-package-always-ensure t)
#+end_src

** The =init.el= entry point

#+begin_src emacs-lisp :tangle "init.el" :mkdirp yes
(defvar osama-emacs-dir (expand-file-name "~/.emacs.d/")
  "The root dir of the Osama Emacs distribution.")

(defvar osama-emacs-modules-dir (expand-file-name "modules" osama-emacs-dir)
  "This directory houses all of the built-in Osama Emacs modules.")

;; Load all .el files from modules directory
(dolist (file (sort (directory-files osama-emacs-modules-dir t "\\.el$") #'string<))
  (load file nil 'nomessage))
#+end_src

* The modules of my Emacs configuration

In this module I define everything broadly related to the aesthetics of Emacs.

** The =osama-emacs-theme.el= module

*** The =osama-emacs-theme.el= Section for UI Basics

#+begin_src emacs-lisp :tangle "modules/osama-emacs-theme.el" :mkdirp yes
(use-package emacs
  :ensure nil
  :init
  ;; Hide UI elements
  (scroll-bar-mode -1)   ;; Disable visible scrollbar
  (tool-bar-mode -1)     ;; Disable the toolbar
  (tooltip-mode -1)      ;; Disable tooltips
  (set-fringe-mode 10)   ;; Give some breathing room
  (menu-bar-mode -1)     ;; Disable the menu bar

  ;; Visible bell instead of audible bell
  (setq visible-bell t)

  ;; Show current column number
  (column-number-mode 1)

  ;; Enable line numbers globally
  (global-display-line-numbers-mode 1)
  ;; Disable line numbers in specific modes
  (dolist (mode '(org-mode-hook
                  term-mode-hook
                  shell-mode-hook
                  eshell-mode-hook))
    (add-hook mode (lambda () (display-line-numbers-mode 0))))

  ;; Make cursor a vertical bar
  (setq-default cursor-type 'bar)

  ;; Highlight current line
  (global-hl-line-mode 1)

  ;; Contextual menu with right mouse button (only in GUI)
  (when (display-graphic-p)
    (context-menu-mode 1)))
#+end_src

*** The =osama-emacs-theme.el= Section for ~Spacious padding~

#+begin_src emacs-lisp :tangle "modules/osama-emacs-theme.el" :mkdirp yes
(use-package spacious-padding
  :custom
  (line-spacing 3)
  (spacious-padding-mode 1))
#+end_src

*** The =osama-emacs-theme.el= Section for ~Toggle Transparency~

#+begin_src emacs-lisp :tangle "modules/osama-emacs-theme.el" :mkdirp yes
(use-package emacs
  :ensure nil
  :init
  ;; Ensure initial frame is fully opaque
  (add-to-list 'default-frame-alist '(alpha . (100 . 100)))

  ;; Function to toggle transparency
  (defun osama-toggle-transparency ()
    (interactive)
    (let ((alpha (frame-parameter nil 'alpha)))
      (set-frame-parameter
       nil 'alpha
       (if (or (eql (cond ((numberp alpha) alpha)
                          ((numberp (cdr alpha)) (cdr alpha))
                          ((numberp (cadr alpha)) (cadr alpha)))
                100)
               (null alpha))  ;; if alpha is not set previously
           '(95 . 90)
         '(100 . 100)))))

  ;; Bind the function to a shortcut
  :bind
  (("C-c t o" . osama-toggle-transparency)))
#+end_src


*** The =osama-emacs-theme.el= Section for Toggle Title Bar & Decorations

#+begin_src emacs-lisp :tangle "modules/osama-emacs-theme.el" :mkdirp yes
(use-package emacs
  :ensure nil
  :init
  ;; Default frame settings
  (add-to-list 'default-frame-alist '(undecorated . nil))
  (add-to-list 'default-frame-alist '(drag-internal-border . 1))
  (add-to-list 'default-frame-alist '(internal-border-width . 10))

  ;; Function to toggle title bar
  (defun osama-frame-toggle-decoration ()
    "Toggle the frame title bar visibility (undecorated)."
    (interactive)
    (let* ((current (frame-parameter nil 'undecorated))
           (new (not current)))
      (set-frame-parameter nil 'undecorated new)))

  ;; Bind the toggle function to a shortcut
  :bind
  (("C-c t f" . osama-frame-toggle-decoration)))
#+end_src

*** The =osama-emacs-theme.el= section for ~theme~

#+begin_src emacs-lisp :tangle "modules/osama-emacs-theme.el" :mkdirp yes
(use-package ef-themes
  :config
  (load-theme 'ef-deuteranopia-light t))
#+end_src

*** The =osama-emacs-theme.el= section for ~modeline~

#+begin_src emacs-lisp :tangle "modules/osama-emacs-theme.el" :mkdirp yes
(use-package emacs
  :ensure nil
  :init
  ;; Header line: buffer name + file path
  (setq-default header-line-format
                '(:eval
                  (let* ((buf (buffer-name))
                         (file (or (buffer-file-name) "")))
                    (propertize
                     (concat buf " — " file)
                     'face 'header-line))))

  ;; Mode line: Evil state + last key + position + UTF-8 indicator + time
  (setq-default mode-line-format
                '("%e"
                  mode-line-front-space
                  ;; Evil state
                  (:eval (propertize (format " %s " evil-state)
                                     'face 'mode-line))
                  (:eval " | ")
                  ;; Last key pressed
                  (:eval (when-let ((keys (this-command-keys-vector)))
                           (propertize
                            (key-description keys)
                            'face '(:weight bold
                                   :inherit mode-line
                                   :box (:line-width 1 :color "gray30")))))
                  (:eval " | ")
                  ;; Position (line:column)
                  mode-line-position
                  "  %p  "
                  ;; UTF-8 indicator as text
                  (:eval (propertize "UTF-8"
                                     'face '(:weight bold :inherit mode-line)))
                  "  "
                  ;; Clock
                  (:eval (propertize
                          (format-time-string " %H:%M ")
                          'face 'mode-line))
                  mode-line-end-spaces)))
#+end_src

** The =osama-emacs-fonts.el= module

*** The =osama-emacs-fonts.el= section for ~nerd-icons~ fonts

#+begin_src emacs-lisp :tangle "modules/osama-emacs-fonts.el" :mkdirp yes
;; Define the folder to save fonts directly inside ~/osama-emacs/emacs-data/fonts
(defvar osama-icons-dir
  (expand-file-name "~/osama-emacs/emacs-data/fonts/")
  "Custom directory to store icon fonts.")

;; Create the folder if it doesn't exist
(unless (file-directory-p osama-icons-dir)
  (make-directory osama-icons-dir t))

;; Helper function to download a font if missing
(defun osama-download-font-if-missing (font-name url)
  "Download FONT-NAME from URL to `osama-icons-dir` if missing."
  (let ((target (expand-file-name font-name osama-icons-dir)))
    (unless (file-exists-p target)
      (url-copy-file url target t)
      (message "Downloaded: %s" font-name))))

;; Download all-the-icons fonts
(use-package all-the-icons
  :config
  (dolist (font
           '(("all-the-icons.ttf" . "https://github.com/domtronn/all-the-icons.el/raw/master/fonts/all-the-icons.ttf")
             ("file-icons.ttf" . "https://github.com/domtronn/all-the-icons.el/raw/master/fonts/file-icons.ttf")
             ("material-design-icons.ttf" . "https://github.com/domtronn/all-the-icons.el/raw/master/fonts/material-design-icons.ttf")
             ("octicons.ttf" . "https://github.com/domtronn/all-the-icons.el/raw/master/fonts/octicons.ttf")
             ("weathericons.ttf" . "https://github.com/domtronn/all-the-icons.el/raw/master/fonts/weathericons.ttf")
             ("fontawesome.ttf" . "https://github.com/domtronn/all-the-icons.el/raw/master/fonts/fontawesome.ttf")))
    (osama-download-font-if-missing (car font) (cdr font))))

;; Download nerd-icons fonts (including NFM.ttf)
(use-package nerd-icons
  :config
  (dolist (font
           '(("NerdFontsSymbolsOnly.ttf" . "https://github.com/rainstormstudio/nerd-icons.el/raw/main/fonts/NerdFontsSymbolsOnly.ttf")
             ("NFM.ttf" . "https://github.com/rainstormstudio/nerd-icons.el/raw/main/fonts/NFM.ttf")))
    (osama-download-font-if-missing (car font) (cdr font))))
#+end_src

*** The =osama-emacs-fonts.el=: Section for Font Customization

#+begin_src emacs-lisp :tangle "modules/osama-emacs-fonts.el" :mkdirp yes
(use-package fontaine
  :hook (after-init . (lambda ()
                        (fontaine-mode 1)
                        (fontaine-set-preset 'osama-fonts)))
  :config
  ;; Define your custom preset
  (setq fontaine-presets
        '((osama-fonts
           :default-family "Fira Code"
           :default-weight regular
           :default-height 100
           :variable-pitch-family "Fira Code"
           :variable-pitch-height 1.0
           :fixed-pitch-family "Fira Code"
           :fixed-pitch-height 100))))

;; Arabic Font
(when (member "STC Forward" (font-family-list))
  (set-fontset-font t 'arabic (font-spec :family "STC Forward")))


;; Create fonts directory if it doesn't exist
(defvar osama-fonts-dir (expand-file-name "~/osama-emacs/emacs-data/fonts/")
  "Directory to store fonts for Emacs.")

(unless (file-directory-p osama-fonts-dir)
  (make-directory osama-fonts-dir t))
#+end_src

** The =osama-emacs-essentials.el= module

This module load basic configurations that apply to most facets of Emacs.

*** The =osama-emacs-essentials.el= Section for Emacs Commands Keybindings

some commands dont have major mode example: (org, dired, consult) so we need to write our custom key 

#+begin_src emacs-lisp :tangle "modules/osama-emacs-essentials.el" :mkdirp yes
(use-package emacs
  :ensure nil
  :bind
  (("C-c f f" . find-file)
   ("C-c b k" . kill-buffer)
   ("C-c b n" . next-buffer)
   ("C-c b p" . previous-buffer)))
#+end_src

*** The =osama-emacs-essentials.el= Section for Session, Auto-Save & Backup Management

#+begin_src emacs-lisp :tangle "modules/osama-emacs-essentials.el" :mkdirp yes
;; Define cache directory
(defvar osama-cache-dir
  (expand-file-name "~/osama-emacs/emacs-cache/")
  "Portable directory for saving Emacs session cache across devices.")

;; Ensure cache directory exists
(defun osama-ensure-cache-directory (dir)
  "Ensure that the cache directory DIR exists, creating it if necessary."
  (unless (file-directory-p dir)
    (make-directory dir t)))

;; Prepare subdirectories
(let ((dirs '("savehist" "recentf" "desktop" "backups" "autosaves")))
  (dolist (sub dirs)
    (osama-ensure-cache-directory (expand-file-name sub osama-cache-dir))))

;; Savehist: command history
(setq savehist-file (expand-file-name "savehist/savehist" osama-cache-dir))
(savehist-mode 1)

;; Recentf: recent files list
(setq recentf-save-file (expand-file-name "recentf/recentf" osama-cache-dir))
(recentf-mode 1)

;; Desktop: full session restore
(setq desktop-path           (list (expand-file-name "desktop" osama-cache-dir))
      desktop-dirname        (expand-file-name "desktop" osama-cache-dir)
      desktop-base-file-name "emacs-desktop")
(desktop-save-mode 1)

;; Backups: store ~ files in backups/
(setq backup-directory-alist
      `((".*" . ,(expand-file-name "backups/" osama-cache-dir)))
      backup-by-copying t
      version-control t
      delete-old-versions t
      kept-new-versions 5
      kept-old-versions 2)

;; Auto-saves: store #files# in autosaves/
(setq auto-save-file-name-transforms
      `((".*" ,(concat (expand-file-name "autosaves/" osama-cache-dir) "\\1") t))
      auto-save-default t
      auto-save-timeout 20
      auto-save-interval 200)

;; Optional: disable lockfiles
(setq create-lockfiles nil)
#+end_src

*** The =osama-emacs-essentials.el= Settings for Better Performance

#+begin_src emacs-lisp :tangle "modules/osama-emacs-essentials.el" :mkdirp yes
(use-package emacs
  :ensure nil
  :init
  ;; Increase GC threshold during startup to speed up launch
  (setq gc-cons-threshold (* 50 1000 1000))
  (add-hook 'emacs-startup-hook
            (lambda () (setq gc-cons-threshold (* 2 1000 1000)))))
#+end_src

*** [Disabled] The =osama-emacs-essentials.el= Section for for UTF-8 Defaults

طبعًا بتحتاج اعداد بسيط لل Utf-8 اذا كنت على Windows 11

قم بفتح =run=
اكتب =intl.cpl=
واختر
Administrative > Change system local... > Arabic (Saudi Arabia) > Beta: Use Unicode UTF-8 for worldwide language support

#+begin_src emacs-lisp :tangle no
(use-package emacs
  :ensure nil ;; built-in
  :init
  ;; اجعل UTF-8 الافتراضي في كل مكان
  (set-language-environment "UTF-8")
  (prefer-coding-system 'utf-8-unix)
  (setq locale-coding-system 'utf-8-unix)
  (setq default-buffer-file-coding-system 'utf-8-unix)

  ;; للتعامل مع العمليات الخارجية (ripgrep, fd ...)
  (set-terminal-coding-system 'utf-8-unix)
  (set-keyboard-coding-system 'utf-8-unix)
  (set-selection-coding-system 'utf-8-unix)

  ;; على Windows: أسماء الملفات والـ clipboard
  (when (eq system-type 'windows-nt)
    (set-clipboard-coding-system 'utf-8-unix)
    (set-file-name-coding-system 'utf-8-unix)))
#+end_src

*** The =osama-emacs-essentials.el= Section for Support Arabic Typing

#+begin_src emacs-lisp :tangle "modules/osama-emacs-essentials.el" :mkdirp yes
(use-package emacs
  :ensure nil
  :init
  ;; Arabic input method
  (setq default-input-method "arabic"))
#+end_src

*** The =osama-emacs-essentials.el= Section for Paragraph Text Direction

#+begin_src emacs-lisp :tangle "modules/osama-emacs-essentials.el" :mkdirp yes
(use-package emacs
  :ensure nil
  :init
  (setq-default bidi-display-reordering t
                bidi-paragraph-direction nil)
  :config
  (defun osama-toggle-text-direction ()
    "Toggle paragraph direction between LTR, RTL, and Auto in any Emacs mode."
    (interactive)
    (setq bidi-paragraph-direction
          (cond
           ((eq bidi-paragraph-direction nil) 'left-to-right)
           ((eq bidi-paragraph-direction 'left-to-right) 'right-to-left)
           ((eq bidi-paragraph-direction 'right-to-left) nil)))
    (message "Paragraph direction now: %s"
             (pcase bidi-paragraph-direction
               ('left-to-right "LTR")
               ('right-to-left "RTL")
               (_ "Auto")))
    (recenter))
  :bind
  ("C-c t r" . osama-toggle-text-direction))
#+end_src

*** The =osama-emacs-essentials.el= settings for ~text-mode~

#+begin_src emacs-lisp :tangle "modules/osama-emacs-essentials.el" :mkdirp yes
(use-package text-mode
  :ensure nil
  :hook
  (text-mode . visual-line-mode)
  :init
  (delete-selection-mode t)
  :custom
  (sentence-end-double-space nil)
  (scroll-error-top-bottom t)
  (save-interprogram-paste-before-kill t))
#+end_src

*** The =osama-emacs-essentials.el= section for ~OpenWith~ package

#+begin_src emacs-lisp :tangle "modules/osama-emacs-essentials.el" :mkdirp yes
;; Open files with external applications
(use-package openwith
  :config
  (openwith-mode t)
  :custom
  (openwith-associations
   '(("\\.\\(?:mp4\\|mkv\\|avi\\)$" "vlc" (file)))))
#+end_src

** The =osama-emacs-completion.el= module

The term “completion” describes a process where user input is assisted by pattern matching algorithms to type out incomplete terms. The most basic way of this model of interaction is what we get in a command-line prompt, where we can hit TAB to expand the word before point to something the program already knows about (e.g ema followed by TAB may complete to emacs).

In Emacs, completion encompasses user interfaces that show the available candidates (the likely options) right away, as well as provide more advanced capabilities for storing the history of previous inputs, displaying helpful annotations next to each candidate, and “completion styles” to control how user input is matched to candidates. Because we use the minibuffer for most common interactions, completion is an integral part of any setup.

*** The =osama-emacs-completion.el= section for ~which-key~

The which-key package provides hints for keys that complete the currently incomplete sequence.

#+begin_src emacs-lisp :tangle "modules/osama-emacs-completion.el" :mkdirp yes
(use-package which-key
  :ensure nil
  :init (which-key-mode)
  :diminish which-key-mode
  :config
  (setq which-key-idle-delay 1)
  (which-key-add-key-based-replacements
    "C-c h" "Help"
    "C-c x" "Text"
    "C-c s" "Search"
    "C-c w" "Windows"
    "C-c e" "Emacs"
    "C-c n" "Notes"
    "C-c o" "Org"
    "C-c o a" "Agenda"
    "C-c f" "Files"
    "C-c b" "Buffers"
    "C-c d" "Dired"
    "C-c t" "Toggles"
    "C-c i" "Insert"
    "C-c a" "Attachments"))
#+end_src


*** The =osama-emacs-completion.el= section for ~vertico~

The ~vertico~ package by Daniel Mendler displays the minibuffer in a vertical layout. Under the hood, it takes care to be responsive and to handle even massive completion tables gracefully. Whereas, say, the built-in completion user interface will suffer from a noticeable performance penalty.

#+begin_src emacs-lisp :tangle "modules/osama-emacs-completion.el" :mkdirp yes
(use-package vertico
  :config
  (setq vertico-cycle t
        vertico-resize nil)
  (vertico-mode 1))
#+end_src

*** The =osama-emacs-completion.el= section for ~marginalia~

The ~marginalia~ package, co-authored by Daniel Mendler and Omar Antolín Camarena, provides helpful annotations to the side of completion candidates. We see its effect, for example, when we call M-x: each command has a brief description next to it (taken from its doc string) as well as a key binding, if it has one.

#+begin_src emacs-lisp :tangle "modules/osama-emacs-completion.el" :mkdirp yes
(use-package marginalia
  :after vertico
  :init
  (marginalia-mode))
#+end_src

*** The =osama-emacs-completion.el= section for ~consult~

~consult~ is another wonderful package by Daniel Mendler. It provides a number of commands that turbocharge the minibuffer with advanced capabilities for filtering, asynchronous input, and previewing of the current candidate’s context.

#+begin_src emacs-lisp :tangle "modules/osama-emacs-completion.el" :mkdirp yes
(use-package consult
  :bind
  (("C-c s s" . consult-line)
   ("C-c s r" . consult-ripgrep)
   ("C-c s f" . consult-fd)
   ("C-c s l" . consult-line-multi)
   ("C-c f f" . consult-find)
   ("C-c f r" . consult-recent-file)
   ("C-c f m" . consult-file-externally)
   ("C-c b b" . consult-buffer)
   ("C-c h o" . consult-outline)
   ("C-c o h" . consult-org-heading)
   ("C-c m m" . consult-mode-command)
   ("C-c m l" . consult-minor-mode)
   ("C-c t t" . consult-theme)
   ("C-c y y" . consult-yank-pop)))
#+end_src

*** The =osama-emacs-completion.el= section for ~orderless~

~orderless~ is a completion style that matches input out-of-order. For example, in pa can match both insert-pair and package-install. Components are space-separated by default. Its design is powerful but avoids many false positives.

#+begin_src emacs-lisp :tangle "modules/osama-emacs-completion.el" :mkdirp yes
(use-package orderless
  :custom
  (completion-styles '(orderless))
  (completion-category-defaults nil))
#+end_src

*** The =osama-emacs-completion.el= section for ~embark~

~embark~ by Omar Antolín Camarena lets you perform context-specific actions via keybindings. embark-act shows a list of actions for the current context (e.g., describe a symbol, manipulate files), while embark-dwim performs the default action. It can also collect minibuffer candidates into a buffer for further operations like in dired or ibuffer.

#+begin_src emacs-lisp :tangle "modules/osama-emacs-completion.el" :mkdirp yes
(use-package embark
  :bind (("C-c ." . embark-act)
         ("C-c ;" . embark-dwim))
  :init
  (setq embark-prompter 'embark-completing-read-prompter))
#+end_src

*** The =osama-emacs-completion.el= section for ~corfu~

Corfu enhances in-buffer completion with a small completion popup. The current candidates are shown in a popup below or above the point, and can be selected by moving up and down. Corfu is the minimalistic in-buffer completion counterpart of the Vertico minibuffer UI.

#+begin_src emacs-lisp :tangle "modules/osama-emacs-completion.el" :mkdirp yes
(use-package corfu
  :init
  (global-corfu-mode))
#+end_src

*** The =osama-emacs-completion.el= section for ~corfu~

Helpful is an alternative to the built-in Emacs help that provides much more contextual information.

#+begin_src emacs-lisp :tangle "modules/osama-emacs-completion.el" :mkdirp yes
(use-package helpful
  :bind
  (("C-c h f" . helpful-function)   ;; Describe function
   ("C-c h c" . helpful-command)    ;; Describe command
   ("C-c h v" . helpful-variable)   ;; Describe variable
   ("C-c h k" . helpful-key)))      ;; Describe key
#+end_src

** The =osama-emacs-org.el= module

At its core, Org is a plain text markup language. By "markup
language", we refer to the use of common characters to apply styling,
such as how a word wrapped in asterisks acquires strong emphasis.
Check the video I link to above on the basics of Org mode.

Though what makes Org powerful is not the markup per se, but the fact
that it has a rich corpus of Emacs Lisp code that does a lot with this
otherwise plain text notation. Some of the headline features:

- Cycle the visibility of any heading and its subheadings. This lets
  you quickly fold a section you do not need to see (or reveal the one
  you care about).
- Mix prose with code in a single document to either make the whole
  thing an actual program or to evaluate/demonstrate some snippets.
- Convert ("export") an Org file to a variety of formats, including
  HTML and PDF.
- Use LaTeX inside of Org files to produce a scientific paper without
  all the markup of LaTeX.
- Manage TODO lists and implement a concomitant methodology of
  labelling task states.
- Quickly shift a "thing" (heading, list item, paragraph, ...) further
  up or down in the file.
- Use tables with formulas as a lightweight alternative to spreadsheet
  software.
- Capture data or fleeting thoughts efficiently using templates.
- Maintain an agenda for all your date-bound activities.
- Clock in and out of tasks, to eventually track how you are spending
  your time.
- Link to files regardless of file type. This includes special links
  such as to an Info manual or an email.

In other words, Org is highly capable and widely considered one of the
killer apps of Emacs.

This section covers the relevant configurations. You will notice that
it is not limited to Org, as some other built-in features are also
relevant here.

*** The =osama-emacs-org.el= section for the ~calendar~

The calendar is technically independent of Org, though it tightly integrates with it.
We can see this when setting timestamps, such as when defining a SCHEDULED or DEADLINE entry for a given heading.
Here, I am simply setting some stylistic preferences.

#+begin_src emacs-lisp :tangle "modules/osama-emacs-org.el" :mkdirp yes
;;; Calendar setup
(use-package calendar
  :ensure nil ;; calendar is built into Emacs
  :commands (calendar)
  :config
  ;; Do not highlight diary entries in the calendar
  (setq calendar-mark-diary-entries-flag nil)

  ;; Show holidays
  (setq calendar-mark-holidays-flag t)

  ;; Do not display a dedicated calendar mode line
  (setq calendar-mode-line-format nil)

  ;; Time format (24-hour)
  (setq calendar-time-display-form
        '(24-hours ":" minutes
          (when time-zone (format "(%s)" time-zone))))

  ;; Start the week on Monday instead of Sunday
  (setq calendar-week-start-day 1)

  ;; Display dates in ISO format (example: 2025-08-18)
  (setq calendar-date-style 'iso)

  ;; Show numeric time zone
  (setq calendar-time-zone-style 'numeric)

  ;; Coordinates (for sunrise/sunset calculation)
  ;; Change them according to your city
  (setq calendar-latitude 15.3694    ; Sana'a (example)
        calendar-longitude 44.1910)

  ;; Time zone
  (setq calendar-standard-time-zone-name "+0300") ; GMT+3
  (setq calendar-daylight-time-zone-name "+0300"))
#+end_src

*** The =osama-emacs-org.el= section about appointment reminders (=appt.el=)

The built-in appt.el handles appointment notifications. It was originally designed for the diary but also integrates well with the Org agenda. I extend this integration so that whenever I add or change a task, the appointments are refreshed through hooks and advice.
Here I only keep minimal settings: I don’t need full agenda details, just a mode line notice showing how many minutes remain until the event.
In Org files, each heading can have an APPT_WARNTIME property (minutes before the event). I use this with org-capture for time-sensitive tasks like coaching sessions.

#+begin_src emacs-lisp :tangle "modules/osama-emacs-org.el" :mkdirp yes
(use-package appt
  :ensure nil ;; built-in in Emacs, no need to install
  :commands (appt-activate) ;; main command to activate the system
  :config
  (setq appt-display-diary nil          ;; do not use the old diary
        appt-display-format nil         ;; default display format
        appt-display-mode-line t        ;; show reminder in the mode line
        appt-display-interval 3         ;; repeat reminder every 3 minutes
        appt-audible nil                ;; sound disabled (set to t for sound)
        appt-warning-time-regexp "appt \\([0-9]+\\)" ;; regex for diary
        appt-message-warning-time 6)    ;; warn 6 minutes before

  (with-eval-after-load 'org-agenda
    (appt-activate 1) ;; enable appt with org-agenda

    ;; convert Org tasks with time info into appt reminders
    (org-agenda-to-appt)))
#+end_src


*** The =osama-emacs-org.el= section with basic Org settings

Org, also known as "Org mode", is one of the potentially most useful
feature sets available to every Emacs user. At its core, Org is a
lightweight markup language: you can have headings and paragraphs,
mark a portion of text with emphasis, produce bullet lists, include
code blocks, and the like. Though what really sets Org apart from
other markup languages is the rich corpus of Emacs Lisp written around
it to do all sorts of tasks with this otherwise plain text format.

With Org you can write technical documents (e.g. the manuals of all my
Emacs packages), maintain a simple or highly sophisticated system for
task management, organise your life using the agenda, write tables
that can evaluate formulas to have spreadsheet functionality, have
embedded LaTeX, evaluate code blocks in a wide range of programming
languages and reuse their results for literate programming, include
the contents of other files into a singular file, use one file to
generate other files/directories with all their contents, and export
the Org document to a variety of formats like =.pdf= and =.odt=.
Furthermore, Org can be used as a lightweight, plain text database, as
each heading can have its own metadata. This has practical
applications in most of the aforementioned.

In short, if something can be done with plain text, Org probably does
it already or has all the elements for piecing it together.

This being Emacs, everything is customisable and Org is a good example
of this. There are a lot of user options for us to tweak things to our
liking. I do as much, though know that Org is perfectly usable without
any configuration. The following sections contain further commentary
on how I use Org.

#+begin_src emacs-lisp :tangle "modules/osama-emacs-org.el" :mkdirp yes
(use-package org
  :ensure nil ;; org built-in
  :init
  ;; Org files directory
  (setq org-directory (expand-file-name "~/osama-emacs/org/"))
  ;; Depth for imenu
  (setq org-imenu-depth 5)
  ;; RET follows links
  (setq org-return-follows-link t)
  ;; Folding without empty line
  (setq org-cycle-separator-lines 0)
  ;; Respect content when inserting heading
  (setq org-insert-heading-respect-content t)
  ;; Ellipsis for folded sections
  (setq org-ellipsis "...")
  ;; Hide emphasis markers globally
  (setq org-hide-emphasis-markers t)
  ;; Hide extra stars in headings
  (setq org-hide-leading-stars t)
  ;; Highlight quote and verse blocks
  (setq org-fontify-quote-and-verse-blocks t)
  ;; Make M-RET insert a new item without splitting the current line
  (setq org-M-RET-may-split-line '((default . nil)))
  ;; Color the entire block delimiter line
  (setq org-fontify-whole-block-delimiter-line t)
  :bind
  (("C-c o l" . org-store-link)
   ("C-c o t" . org-toggle-link-display)
   ("C-c o o" . org-open-at-point-global)))


  ;; Show emphasis markers only while editing
  (use-package org-appear
    :hook (org-mode . org-appear-mode))

  ;; Modern appearance
  (use-package org-modern
    :disabled t
    :hook (org-mode . org-modern-mode)
    :custom
    (org-modern-table nil)
    (org-modern-keyword nil)
    (org-modern-timestamp nil)
    (org-modern-priority nil)
    (org-modern-checkbox nil)
    (org-modern-tag nil)
    (org-modern-block-name nil)
    (org-modern-footnote nil)
    (org-modern-internal-target nil)
    (org-modern-radio-target nil)
    (org-modern-statistics nil)
    (org-modern-progress nil))

  ;; Superstar bullets
  (use-package org-superstar
    :hook (org-mode . org-superstar-mode)
    :config
    ;; Replace default heading stars with custom bullets
    (setq org-superstar-headline-bullets-list '("◉" "○" "●" "◎" "◆" "▶")))

;; Font setup for org headings and bullets
(defun osama-org-font-setup ()
  ;; Replace dashes with bullets
  (font-lock-add-keywords 'org-mode
    '(("^ *\\([-]\\) "
       (0 (prog1 ()
            (compose-region (match-beginning 1)
                            (match-end 1) "•"))))))
  ;; Set heading sizes
  (let ((family (face-attribute 'default :family)))
    (dolist (face '((org-level-1 . 1.2)
                    (org-level-2 . 1.1)
                    (org-level-3 . 1.05)
                    (org-level-4 . 1.0)
                    (org-level-5 . 1.0)
                    (org-level-6 . 1.0)
                    (org-level-7 . 1.0)
                    (org-level-8 . 1.0)))
      (set-face-attribute (car face) nil
                          :family family
                          :weight 'bold
                          :height (cdr face)))))
;; Change document title size
(custom-set-faces
 '(org-document-title ((t (:height 2.0 :underline nil)))))

;; Hook font setup into org-mode
(add-hook 'org-mode-hook #'osama-org-font-setup)
#+end_src


*** The =osama-emacs-org.el= section for ~agenda~ and ~TODO~

#+begin_src emacs-lisp :tangle "modules/osama-emacs-org.el" :mkdirp yes
(use-package org
  :ensure nil
  :config
  (setq org-log-done 'time)
  (setq org-log-into-drawer t)
  (setq org-directory "~/osama-emacs/org/agenda/")
  (setq org-agenda-files (list org-directory))
  (setq org-todo-keywords
        '((sequence "TODO(t)" "|" "CANCEL(c!)" "DONE(d!)"))))
#+end_src

*** The =osama-emacs-org.el= section for ~org-capture~


** The =osama-emacs-denote.el= module

*** The =osama-emacs-denote.el= section for basic settings

لماذا استخدمنا denote
- لان الملاحظات عبارة عن ملاحظات صغير atom notes وتقوم بالربط بينهن حتى لو كان تعريف صغير تخليه ملاحظة لحالها
- no database
- id method can even be writted in you hand note book
- you can use it from any emacs distro like doom or vanilla because its plain text
- unique id because we can change title as we wish without breaking nites link

نصائح
- DONT - use headings link because its compicted things and atomic notes
- يفصل ان تكتب ملاحظاتك في الحياة وفي الجامعة مثلا في دفتر وتستخدم denotr file naming scheme مثلا التاريخ والkeywords و title تبع المءكرة ولو كان تعريف صغير
- استخدم الkeywords بصيغة الجمع
- خلي كل الملاحظات والملفات بنفس المجلد لانك بتحتاج تعمل تصنيف ايضا للصور والفيدوهات والثوتيات وملفات pdfs
- استخدم ااربط بشكل كبير ضروري لان الملاحظات عبارة عن atom

#+begin_src emacs-lisp :tangle "modules/osama-emacs-denote.el" :mkdirp yes
(use-package denote
  :hook (dired-mode . denote-dired-mode)
  :bind
  (("C-c n n" . denote)
   ("C-c n r" . denote-rename-file)
   ("C-c n l" . denote-link)
   ("C-c n b" . denote-backlinks)
   ("C-c n d" . denote-dired))
  :config
  (setq denote-directory (expand-file-name "~/osama-emacs/notes/"))

  ;; Automatically rename Denote buffers when opening them so that
  ;; instead of their long file name they have, for example, a literal
  ;; "[D]" followed by the file's title.  Read the doc string of
  ;; `denote-rename-buffer-format' for how to modify this.
  (denote-rename-buffer-mode 1))
#+end_src

*** The =osama-emacs-denote.el= section for ~consult-denote~

#+begin_src emacs-lisp :tangle "modules/osama-emacs-denote.el" :mkdirp yes
(use-package consult-denote
  :demand t
  :bind
  (("C-c n f" . consult-denote-find)
   ("C-c n g" . consult-denote-grep))
  :custom
  ;; force consult-denote to use consult-fd instead of find
  (consult-denote-find-command #'consult-fd)
  ;; force consult-denote to use consult-ripgrep instead of grep
  (consult-denote-grep-command #'consult-ripgrep)
  :config
  (consult-denote-mode 1))
#+end_src

** The =osama-emacs-markdown.el= module

*** The =osama-emacs-markdown.el= section for Basic Settings

#+begin_src emacs-lisp :tangle "modules/osama-emacs-markdown.el" :mkdirp yes
(use-package markdown-mode
  :ensure t
  :mode ("README\\.md\\'" . gfm-mode)
  :init (setq markdown-command "multimarkdown")
  :bind (:map markdown-mode-map
         ("C-c C-e" . markdown-do)))
#+end_src

** The =osama-emacs-evil.el= module

*** The =osama-emacs-evil.el= section for =evil-mode= & =evil-collection=

#+begin_src emacs-lisp :tangle "modules/osama-emacs-evil.el" :mkdirp yes
;;; Evil-mode setup
(use-package evil
  :init
  (setq evil-want-integration t          ;; integrate with other packages
        evil-want-keybinding nil         ;; don't load default keybindings
        evil-want-C-u-scroll t           ;; C-u scroll up
        evil-want-C-i-jump nil)          ;; disable C-i jump
  :config
  (setq evil-mode-line-format nil)       ;; ✅ بعد تحميل الحزمة
  (evil-mode 1)

  ;; Global keybindings
  (global-set-key (kbd "<escape>") 'keyboard-escape-quit)
  (define-key evil-insert-state-map (kbd "C-g") 'evil-normal-state)

  ;; Motion keys: move by visual lines
  (evil-global-set-key 'motion "j" 'evil-next-visual-line)
  (evil-global-set-key 'motion "k" 'evil-previous-visual-line)

  ;; Set initial state for specific modes
  (evil-set-initial-state 'messages-buffer-mode 'normal)
  (evil-set-initial-state 'dashboard-mode 'normal))

;;; Evil-collection setup (integrates evil with other Emacs modes)
(use-package evil-collection
  :after evil
  :config
  (evil-collection-init))
#+end_src

*** The =osama-emacs-evil.el= section for general leader key

#+begin_src emacs-lisp :tangle "modules/osama-emacs-evil.el" :mkdirp yes
(use-package general
  :config
  (general-define-key
   :keymaps 'normal
   "SPC"   (general-simulate-key "C-c")))
#+end_src

** The =osama-emacs-dired.el= module

#+begin_src emacs-lisp :tangle "modules/osama-emacs-dired.el" :mkdirp yes
(use-package dired
  :ensure nil ;; built-in package
  :commands (dired dired-jump)
  :custom
  (dired-listing-switches "-alh") ;; human-readable sizes
  (dired-dwim-target t)           ;; smart target when copying/moving
  (dired-recursive-copies 'always)
  (dired-recursive-deletes 'top)
  (dired-auto-revert-buffer t)    ;; auto refresh on changes
  :bind
  (("C-c d d" . dired)
   ("C-c d j" . dired-jump)))
   
(use-package dired-x
  :ensure nil
  :after dired
  :config
  (setq dired-omit-files "^\\.?#\\|^\\.")) ;; hide clutter files like .#temp

(use-package all-the-icons-dired
  :hook (dired-mode . all-the-icons-dired-mode))
#+end_src

** The =osama-emacs-window.el= module

*** The =osama-emacs-window.el= section for windows

#+begin_src emacs-lisp :tangle "modules/osama-emacs-window.el" :mkdirp yes
(use-package emacs
  :ensure nil
  :bind
  (("C-c w w" . other-window)                ;; next window

   ;; Split windows
   ("C-c w s" . split-window-below)          ;; split below (horizontal)
   ("C-c w v" . split-window-right)          ;; split right (vertical)

   ;; Delete windows
   ("C-c w d" . delete-window)               ;; delete current window
   ("C-c w D" . kill-buffer-and-window)      ;; delete window + buffer
   ("C-c w o" . delete-other-windows)        ;; keep only current window

   ;; Resize windows
   ("C-c w {" . shrink-window-horizontally)
   ("C-c w }" . enlarge-window-horizontally)
   ("C-c w ^" . enlarge-window)

   ;; Move between windows with arrows
   ("C-c w h" . windmove-left)
   ("C-c w l" . windmove-right)
   ("C-c w k" . windmove-up)
   ("C-c w j" . windmove-down)))
#+end_src

*** The =osama-emacs-window.el= section for ~tabs~

#+begin_src emacs-lisp :tangle "modules/osama-emacs-window.el" :mkdirp yes
(use-package emacs
  :ensure nil
  :init
  (tab-bar-mode 1)
  (setq tab-bar-show t
        tab-bar-new-tab-choice "*scratch*"
        tab-bar-tab-name-truncated-max 20
        tab-bar-close-button-show nil
        tab-bar-back-button-show nil)
  
  ;; Functions to jump to tab by number
  (dotimes (i 9)
    (let ((n (1+ i)))
      (defalias (intern (format "tab-goto-%d" n))
        `(lambda ()
           (interactive)
           (tab-bar-select-tab ,n)))))

  ;; Keybindings C-c t 1 .. C-c t 9
  :bind
  (("C-c 1" . tab-goto-1)
   ("C-c 2" . tab-goto-2)
   ("C-c 3" . tab-goto-3)
   ("C-c 4" . tab-goto-4)
   ("C-c 5" . tab-goto-5)
   ("C-c 6" . tab-goto-6)
   ("C-c 7" . tab-goto-7)
   ("C-c 8" . tab-goto-8)
   ("C-c 9" . tab-goto-9)
   ;; Optional: new / close / next / prev
   ("C-c t i" . tab-new)
   ("C-c t c" . tab-close)
   ("C-c t n" . tab-next)
   ("C-c t p" . tab-previous)))
#+end_src

** The =osama-emacs-dashboard.el= module

#+begin_src emacs-lisp :tangle "modules/osama-emacs-dashboard.el" :mkdirp yes
(use-package dashboard
  :config
  (dashboard-setup-startup-hook)

  ;; Banner
  (setq dashboard-startup-banner 'official)
  (setq dashboard-banner-logo-title "Welcome to Emacs, Osama!")

  ;; Center content
  (setq dashboard-center-content t)

  ;; Enable icons
  (setq dashboard-set-heading-icons t)
  (setq dashboard-set-file-icons t)

  ;; Customize items with icons and shortcuts
  (setq dashboard-items '((recents  . 5)
                          (projects . 5)
                          (bookmarks . 5)))

  ;; Add custom widget for shortcuts
  (setq dashboard-item-generators
        '((recents . (lambda (list-size)
                       (dashboard-insert-heading " Recent Files" 'all-the-icons-blue)
                       (dashboard-insert-recents list-size)))
          (projects . (lambda (list-size)
                        (dashboard-insert-heading " Projects" 'all-the-icons-green)
                        (dashboard-insert-projects list-size)))
          (bookmarks . (lambda (list-size)
                         (dashboard-insert-heading " Bookmarks" 'all-the-icons-orange)
                         (dashboard-insert-bookmarks list-size)))))

  ;; Shortcut hints
  (setq dashboard-set-shortcuts t)
  (setq dashboard-shortcut-list
        '(("SPC f r" . recents)
          ("SPC f p" . projects)
          ("SPC f b" . bookmarks))))
#+end_src



** The =osama-emacs-system-custom.el= module

*** The =osama-emacs-system-custom.el= module section for android

*** The =osama-emacs-system-custom.el= module section for windows

* Android Section For Personal Settings

* The Personal Functions
