#+title: GNU Emacs configuration
#+author: Osama Ghourab
#+email: osamaghox@gmail.com
#+language: en
#+options: ':t toc:nil num:t author:t email:t
#+startup: content indent
#+macro: latest-export-date (eval (format-time-string "%F %T %z"))
#+macro: word-count (eval (count-words (point-min) (point-max)))

* The early initialisation of Emacs (=early-init.el=)

This is the first file that Emacs reads when starting up. It should contain code that does not depend on any package or the proportions of the Emacs frame. In general, this early initialisation file is meant to set up a few basic things before Emacs produces the initial frame by delegating to the init.el

** The =early-init.el= section to set PATH and system tools

#+begin_src emacs-lisp :tangle "early-init.el" :mkdirp yes
;; Detect system type and add appropriate paths
(let ((path-sep (if (eq system-type 'windows-nt) ";" ":")))

  ;; Android (Termux) settings
  (when (string-equal system-type "android")
    (setenv "PATH" (format "%s%s%s"
                           "/data/data/com.termux/files/usr/bin"
                           path-sep
                           (getenv "PATH")))
    (setenv "LD_LIBRARY_PATH" (format "%s:%s"
                                      "/data/data/com.termux/files/usr/lib"
                                      (getenv "LD_LIBRARY_PATH")))
    (push "/data/data/com.termux/files/usr/bin" exec-path))

  ;; Windows settings
  (when (eq system-type 'windows-nt)
    ;; Git
    (let ((tools-dir (expand-file-name "~/osama-emacs/emacs-data/tools/")))
      (add-to-list 'exec-path (concat tools-dir "git/cmd"))
      (setenv "PATH" (concat (expand-file-name (concat tools-dir "git/cmd/"))
                             path-sep
                             (getenv "PATH")))

      ;; fd (file search tool)
      (add-to-list 'exec-path (concat tools-dir "fd/"))

      ;; ripgrep
      (add-to-list 'exec-path (concat tools-dir "ripgrep/")))))
#+end_src

* The main initialisation of Emacs (=init.el=)

This is where I define the Lisp macros used in my setup and load all the invidiual modules.

** The =init.el= entry point

#+begin_src emacs-lisp :tangle "init.el" :mkdirp yes
(defvar osama-emacs-dir (expand-file-name "~/.emacs.d/")
  "The root dir of the Osama Emacs distribution.")

(defvar osama-emacs-modules-dir (expand-file-name "modules" osama-emacs-dir)
  "This directory houses all of the built-in Osama Emacs modules.")
#+end_src

** The =init.el= settings for packages (=package.el=)

The =package.el= is built into Emacs and is perfectly fine for my
use-case. We do not need to load it explicitly, as it will be called
by ~use-package~ when it needs it

#+begin_src emacs-lisp :tangle "init.el" :mkdirp yes
;; Prevent Emacs from loading packages before init
(setq package-enable-at-startup nil)

(require 'package)

;; Package repositories
(setq package-archives
      '(("melpa" . "https://melpa.org/packages/")
        ("org"   . "https://orgmode.org/elpa/")
        ("elpa"  . "https://elpa.gnu.org/packages/")))

(package-initialize)

;; Install use-package if not installed
(unless (package-installed-p 'use-package)
  (unless package-archive-contents
    (package-refresh-contents))
  (package-install 'use-package))

(require 'use-package)

;; Automatically install declared packages
(setq use-package-always-ensure t)

(provide 'osama-emacs-packages)
#+end_src







This module load basic configurations that apply to most facets of Emacs.

* The modules of my Emacs configuration

In this module I define everything broadly related to the aesthetics of Emacs.

** The =osama-emacs-theme.el= module

*** The =osama-emacs-theme.el= section for =theme=

#+begin_src emacs-lisp :tangle "modules/osama-emacs-theme.el" :mkdirp yes
(use-package doom-themes
  :init
  (load-theme 'doom-dracula t))
#+end_src

*** The =osama-emacs-theme.el= section for =modeline=
#+begin_src emacs-lisp :tangle "modules/osama-emacs-theme.el" :mkdirp yes
(use-package doom-modeline
  :ensure t
  :init
  (doom-modeline-mode 1)
  :custom
  (doom-modeline-height 40)
  (doom-modeline-bar-width 3)
  (doom-modeline-buffer-file-name-style 'truncate-with-project)
  (doom-modeline-icon t)
  (doom-modeline-major-mode-icon t)
  (doom-modeline-minor-modes nil)
  (doom-modeline-enable-word-count t)
  (doom-modeline-indent-info t))
#+end_src

*** The =osama-emacs-theme.el= section for =nerd-icons= fonts

#+begin_src emacs-lisp :tangle "modules/osama-emacs-theme.el" :mkdirp yes
;; Define the folder to save fonts directly inside fonts
(defvar osama-emacs-icons-dir
  (expand-file-name "sync-thing/online-sync/emacs/emacs-data/fonts/"
                    (getenv "HOME"))
  "Custom directory to store icon fonts.")

;; Create the folder if it doesn't exist
(unless (file-directory-p osama-emacs-icons-dir)
  (make-directory osama-emacs-icons-dir t))

;; Helper function to download a font if missing
(defun osama/download-font-if-missing (font-name url)
  "Download FONT-NAME from URL to `osama-emacs-icons-dir` if missing."
  (let ((target (expand-file-name font-name osama-emacs-icons-dir)))
    (unless (file-exists-p target)
      (url-copy-file url target t)
      (message "Downloaded: %s" font-name))))

;; Download all-the-icons fonts
(use-package all-the-icons
  :config
  (dolist (font
           '(("all-the-icons.ttf" . "https://github.com/domtronn/all-the-icons.el/raw/master/fonts/all-the-icons.ttf")
             ("file-icons.ttf" . "https://github.com/domtronn/all-the-icons.el/raw/master/fonts/file-icons.ttf")
             ("material-design-icons.ttf" . "https://github.com/domtronn/all-the-icons.el/raw/master/fonts/material-design-icons.ttf")
             ("octicons.ttf" . "https://github.com/domtronn/all-the-icons.el/raw/master/fonts/octicons.ttf")
             ("weathericons.ttf" . "https://github.com/domtronn/all-the-icons.el/raw/master/fonts/weathericons.ttf")
             ("fontawesome.ttf" . "https://github.com/domtronn/all-the-icons.el/raw/master/fonts/fontawesome.ttf"))))
    (osama/download-font-if-missing (car font) (cdr font))))

;; Download nerd-icons fonts (including NFM.ttf)
(use-package nerd-icons
  :config
  (dolist (font
           '(("NerdFontsSymbolsOnly.ttf" . "https://github.com/rainstormstudio/nerd-icons.el/raw/main/fonts/NerdFontsSymbolsOnly.ttf")
             ("NFM.ttf" . "https://github.com/rainstormstudio/nerd-icons.el/raw/main/fonts/NFM.ttf"))))
    (osama/download-font-if-missing (car font) (cdr font))))
#+end_src



*** The =osama-emacs-theme.el=: Section for Font Customization

#+begin_src emacs-lisp :tangle "modules/osama-emacs-theme.el" :mkdirp yes
(defvar osama-emacs-preferred-font "Fira Code"
  "Preferred font in Emacs.")

(when (find-font (font-spec :name osama-emacs-preferred-font))
  ;; Main font
  (set-face-attribute 'default nil :font osama-emacs-preferred-font :height 120)
  (set-face-attribute 'fixed-pitch nil :font osama-emacs-preferred-font) ;; For code and tables
  (set-face-attribute 'variable-pitch nil :font osama-emacs-preferred-font :height 100)

  ;; Different font for Arabic
  (set-fontset-font t 'arabic (font-spec :name "STC Forward")))

;; Create fonts directory if it doesn't exist
(defvar osama-emacs-fonts-dir (expand-file-name "~/osama-emacs/emacs-data/fonts/")
  "Directory to store fonts for Emacs.")

(unless (file-directory-p osama-emacs-fonts-dir)
  (make-directory osama-emacs-fonts-dir t))
#+end_src

** The =osama-emacs-essentials.el= module

This module load basic configurations that apply to most facets of Emacs. Many of my own custom libraries are loaded here 

*** The =osama-emacs-essentials.el= Section for Hide Tool bar

#+begin_src emacs-lisp :tangle "modules/osama-emacs-essentials.el" :mkdirp yes
(scroll-bar-mode -1)        ; Disable visible scrollbar
(tool-bar-mode -1)          ; Disable the toolbar
(tooltip-mode -1)           ; Disable tooltips
(set-fringe-mode 10)        ; Give some breathing room
(menu-bar-mode -1)          ; Disable the menu bar
#+end_src

*** The =osama-emacs-essentials.el= Section for UI Basics

#+begin_src emacs-lisp :tangle "modules/osama-emacs-essentials.el" :mkdirp yes
;; Visible bell
(setq visible-bell t)

;; Show current column number
(column-number-mode)

;; Enable line numbers globally and disable in specific modes
(global-display-line-numbers-mode t)
(dolist (mode '(org-mode-hook
                term-mode-hook
                shell-mode-hook
                eshell-mode-hook))
  (add-hook mode (lambda () (display-line-numbers-mode 0))))

;; Make cursor a vertical bar
(setq-default cursor-type 'bar)

;; Highlight current line
(global-hl-line-mode 1)
#+end_src

*** The =osama-emacs-essentials.el= Section for Session, Auto-Save & Backup Management

#+begin_src emacs-lisp :tangle "modules/osama-emacs-essentials.el" :mkdirp yes
  ;; Define cache directory
  (defvar osama-emacs-cache-dir
    (expand-file-name "~/osama-emacs/emacs-cache/")
    "Portable directory for saving Emacs session cache across devices.")

  ;; Ensure directory exists
  (defun osama-ensure-directory (dir)
    (unless (file-directory-p dir)
      (make-directory dir t)))

  ;; Prepare subdirectories
  (let ((dirs '("savehist" "recentf" "desktop" "backups" "autosaves")))
    (dolist (sub dirs)
      (osama-ensure-directory (expand-file-name sub osama-emacs-cache-dir))))

  ;; Savehist: command history
  (setq savehist-file (expand-file-name "savehist/savehist" osama-emacs-cache-dir))
  (savehist-mode 1)
  
  ;; Recentf: recent files list
  (setq recentf-save-file (expand-file-name "recentf/recentf" osama-emacs-cache-dir))
  (recentf-mode 1)

  ;; Desktop: full session restore
  (setq desktop-path           (list (expand-file-name "desktop" osama-emacs-cache-dir))
        desktop-dirname        (expand-file-name "desktop" osama-emacs-cache-dir)
        desktop-base-file-name "emacs-desktop")
  (desktop-save-mode 1)

  ;; Backups: store ~ files in backups/
  (setq backup-directory-alist
        `((".*" . ,(expand-file-name "backups/" osama-emacs-cache-dir)))
        backup-by-copying t
        version-control t
        delete-old-versions t
        kept-new-versions 5
        kept-old-versions 2)

  ;; Auto-saves: store #files# in autosaves/
  (setq auto-save-file-name-transforms
        `((".*" ,(concat (expand-file-name "autosaves/" osama-emacs-cache-dir) "\\1") t))
        auto-save-default t
        auto-save-timeout 20
        auto-save-interval 200)

  ;; Optional: disable lockfiles
  (setq create-lockfiles nil)
#+end_src

*** The =osama-emacs-essentials.el= Settings for Better Performance

#+begin_src emacs-lisp :tangle "modules/osama-emacs-essentials.el" :mkdirp yes
;; Increase GC threshold during startup to speed up launch
  (setq gc-cons-threshold (* 50 1000 1000))
  (add-hook 'emacs-startup-hook
            (lambda () (setq gc-cons-threshold (* 2 1000 1000))))
#+end_src

*** The =osama-emacs-essentials.el= Section for Support Arabic Filenames

#+begin_src emacs-lisp :tangle "modules/osama-emacs-essentials.el" :mkdirp yes
  (prefer-coding-system 'utf-8)
  (setq default-buffer-file-coding-system 'utf-8)
#+end_src

*** The =osama-emacs-essentials.el= Section for Paragraph Text Direction

#+begin_src emacs-lisp :tangle "modules/osama-emacs-essentials.el" :mkdirp yes
;; Enable text reordering for right-to-left (RTL) languages
(setq-default bidi-display-reordering t)

;; Default mode for all files (paragraph direction is automatic)
(setq-default bidi-paragraph-direction nil)

(defun osama-emacs-toggle-bidi-paragraph-direction ()
  "Toggle paragraph direction between LTR, RTL, and Auto in any Emacs mode."
  (interactive)
  (setq bidi-paragraph-direction
        (cond
         ((eq bidi-paragraph-direction nil) 'left-to-right)
         ((eq bidi-paragraph-direction 'left-to-right) 'right-to-left)
         ((eq bidi-paragraph-direction 'right-to-left) nil)))
  (message "Paragraph direction now: %s"
           (pcase bidi-paragraph-direction
             ('left-to-right "LTR")
             ('right-to-left "RTL")
             (_ "Auto")))

  (recenter))

;; Set a global shortcut to toggle paragraph direction in all Emacs modes
(global-set-key (kbd "C-c r") #'osama-emacs-toggle-bidi-paragraph-direction)
#+end_src

*** The =osama-emacs-essentials.el= Section for 

** The =osama-emacs-completion.el= module

** The =osama-emacs-dired.el= module

** The =osama-emacs-windows.el= module

** The =osama-emacs-org.el= module

** The =osama-emacs-system-custom= module

*** The =osama-emacs-android-custom= module

*** The =osama-emacs-windows-custom= module

* Android Section For Personal Settings

* The Personal Functions
