#+title: GNU Emacs configuration
#+author: Osama Ghourab
#+email: osamaghox@gmail.com
#+language: en
#+options: ':t toc:nil num:t author:t email:t
#+startup: content indent
#+macro: latest-export-date (eval (format-time-string "%F %T %z"))
#+macro: word-count (eval (count-words (point-min) (point-max)))



واصل يا عمنا! طيب، خلينا نسوي لك تقسيم واضح للـ Emacs config على شكل modules بحيث كل وحدة تغطي جانب محدد، وبهذا ما تحتار وين تضيف أي package أو إعداد جديد. أنا رح أعطيك مثال عملي يمكن تستخدمه مباشرة:


---

1. الهيكل العام للمجلد

~/.emacs.d/
│
├─ init.el          ;; الملف الرئيسي يحمّل كل modules
├─ early-init.el    ;; تحميل أي إعدادات مبكرة
└─ lisp/            ;; كل modules هنا
    ├─ osama-emacs-themes.el
    ├─ osama-emacs-packages.el
    ├─ osama-emacs-ui.el
    ├─ osama-emacs-keybindings.el
    ├─ osama-emacs-org.el
    ├─ osama-emacs-denote.el
    ├─ osama-emacs-completion.el
    ├─ osama-emacs-lsp.el
    ├─ osama-emacs-vc.el
    └─ osama-emacs-utils.el


---

2. شرح كل module

osama-emacs-themes.el

كل شيء يخص المظهر (themes, fonts, modeline, icons)


osama-emacs-packages.el

تثبيت وإعداد الـ packages (use-package, quelpa, straight.el)


osama-emacs-ui.el

إعداد الواجهة: sidebar, dashboard, line numbers, tabs, scrolling


osama-emacs-keybindings.el

كل الـ keybindings الشخصية، shortcuts، وleader keys


osama-emacs-org.el

org-mode، org-roam، org-babel


osama-emacs-denote.el

كل شيء يخص denote: notes, PDFs, videos


osama-emacs-completion.el

Ivy, Vertico, Helm, company-mode


osama-emacs-lsp.el

إعداد LSP (lsp-mode, eglot, dap-mode)


osama-emacs-vc.el

git, magit, diff-hl، أي شيء يخص version control


osama-emacs-utils.el

أي أدوات إضافية: file management, snippets, org-capture templates




---

3. كيفية تحميل modules في init.el

;; init.el
(add-to-list 'load-path (expand-file-name "lisp" user-emacs-directory))

;; Modules
(require 'osama-emacs-packages)
(require 'osama-emacs-themes)
(require 'osama-emacs-ui)
(require 'osama-emacs-keybindings)
(require 'osama-emacs-org)
(require 'osama-emacs-denote)
(require 'osama-emacs-completion)
(require 'osama-emacs-lsp)
(require 'osama-emacs-vc)
(require 'osama-emacs-utils)


---

4. نصيحة تنظيم إضافية

لو أردت إضافة package جديد:
إذا يخص المظهر → themes.el
إذا يخص org-mode → org.el
لو يخص productivity أو notes → denote.el أو utils.el

حاول كل module يكون مسؤول فقط عن شيء واحد، هذا يسهل صيانة config بعد 5 سنوات.



---

إذا أحب، أقدر أسوي لك نسخة جاهزة من هذه modules مع الهيكل الأساسي بحيث تقدر تبدأ تضيف إعداداتك مباشرة بدون لخبطة.

تحب أسويها لك؟






*https://github.com/protesilaos/dotfiles/tree/master/emacs/.emacs.d/prot-emacs-modules

* The early initialisation of Emacs (early-init.el)

This is the first file that Emacs reads when starting up. It should contain code that does not depend on any package or the proportions of the Emacs frame. In general, this early initialisation file is meant to set up a few basic things before Emacs produces the initial frame by delegating to the init.el

** The =early-init.el= section to set PATH and system tools

#+begin_src emacs-lisp :tangle "early-init.el" :mkdirp yes
;; Detect system type and add appropriate paths
(let ((path-sep (if (eq system-type 'windows-nt) ";" ":")))

  ;; Android (Termux) settings
  (when (string-equal system-type "android")
    (setenv "PATH" (format "%s%s%s"
                           "/data/data/com.termux/files/usr/bin"
                           path-sep
                           (getenv "PATH")))
    (setenv "LD_LIBRARY_PATH" (format "%s:%s"
                                      "/data/data/com.termux/files/usr/lib"
                                      (getenv "LD_LIBRARY_PATH")))
    (push "/data/data/com.termux/files/usr/bin" exec-path))

  ;; Windows settings
  (when (eq system-type 'windows-nt)
    ;; Git
    (add-to-list 'exec-path "~/sync-thing/online-sync/emacs/emacs-data/tools/git/cmd")
    (setenv "PATH" (concat (expand-file-name "~/sync-thing/online-sync/emacs/emacs-data/tools/git/cmd/")
                           path-sep
                           (getenv "PATH")))

    ;; fd (file search tool)
    (add-to-list 'exec-path "~/sync-thing/online-sync/emacs/emacs-data/tools/fd/")

    ;; ripgrep
    (add-to-list 'exec-path "~/sync-thing/online-sync/emacs/emacs-data/tools/ripgrep/")))
#+end_src

* The main initialisation of Emacs (init.el)

This is where I define the Lisp macros used in my setup and load all the invidiual modules.


** The =init.el= entry point

#+begin_src emacs-lisp :tangle "init.el" :mkdirp yes
(add-to-list 'load-path (expand-file-name "lisp" user-emacs-directory))

(require 'osama-emacs-core)
(require 'osama-emacs-packages)
(require 'osama-emacs-ui)
#+end_src


* The modules of my Emacs configuration

In this module I define everything broadly related to the aesthetics of Emacs.

** The =osama-emacs-core.el=

*** The







