* Doom Emacs Native in Windows

** Step 1 - Installing Important tools

*** Emacs App

Doom Emacs can't be used without Emacs app, so we need to download the installer from the website

[[https://www.gnu.org/software/emacs/download.html][GNU Emacs Official Site]]

Download it from ~nearby GNU mirror~
Example: ~emacs-30.2-installer.exe~

After that, install it normally and make sure the installation path is Program Files
Example: ~C:\Program Files\Emacs~

*** Git Tool

We need Git to download Doom repo to our PC, and we will use it for other Emacs tools like Magit

Download it from here:

[[https://git-scm.com/downloads/win][Git Official Site]]

Standalone Installer:
~Git for Windows/x64 Setup.~

Install it to ~C:\Tools~ and name it =Git=

*** fd Tool

We need ~fd~ because it can search by file name and it's very fast

Download it from here:
[[https://github.com/sharkdp/fd/releases][fd releases on GitHub]]

Make sure you download ~windows-gnu~

Extract folder to ~C:\Tools~ and name it =fd=

*** ripgrep Tool

We need ~ripgrep~ because it can search texts in files, which is pretty useful in some cases

Download it from here:

[[https://github.com/BurntSushi/ripgrep/releases][ripgrep releases on GitHub]]

Make sure you download ~windows-gnu~

Extract folder to ~C:\Tools~ and name it =ripgrep=


** Step 2 - Edit system environment variables

When we install tools like fd or ripgrep, Emacs (and Doom) needs to find them no matter where they are on the system.
By adding their installation folders to the system environment variables (PATH), we make these tools accessible from any terminal or program without typing the full path every time.

Go to Control Panel -> User Accounts -> Change my environment variables.

New, type =HOME= and set your ~C:\Users\USERNAME~ and OK.  
Select =Path=, =Edit= and add your ~C:\Program Files\Emacs\(your-emacs-version)\bin~ folder and OK.
Select =Path=, =Edit= and add your ~C:\Tools\ripgrep~ folder and OK.  
Select =Path=, =Edit= and add your ~C:\Tools\fd~ folder and OK.  
Click OK.

** Step 3 - Clone Doom repo

*** Open =git-bash.exe=

- Go to your home folder by typing:

#+BEGIN_SRC bash
cd ~
#+END_SRC

- Then clone the Doom repo:

#+BEGIN_SRC bash
git clone https://github.com/doomemacs/doomemacs ~/.emacs.d
#+END_SRC

- After the download is complete, type:

#+BEGIN_SRC bash
cd ~/.emacs.d/bin
#+END_SRC

- Then install Doom by typing:

#+BEGIN_SRC bash
./doom install
#+END_SRC

- If everything is fine, Doom is now installed.

- Go again to:

#+BEGIN_SRC bash
cd ~/.emacs.d/bin
#+END_SRC

- Just in case, run:

#+BEGIN_SRC bash
./doom sync
#+END_SRC

- Go to Control Panel -> User Accounts -> Change my environment variables.
  - Select =Path=, then =Edit= and add: ~C:\Users\USERNAME\.emacs.d\bin~, click OK -> OK.

*Now you can start Emacs and will see the Doom dashboard!*

* Step 4 - Install Nerd Icons & All The Icons Fonts

To make sure all icons in Emacs display correctly, you need to install additional fonts. These fonts provide the symbols used in themes, modelines, and various packages. Without them, some icons may appear as empty boxes or incorrect characters.

- **Nerd Fonts:** A collection of patched fonts including popular icon sets.
- **All The Icons Fonts:** Provides extra icons used by packages like `all-the-icons.el`.

Download and install the fonts from the links below, then restart Emacs to see the icons properly.

[[https://github.com/rainstormstudio/nerd-icons.el/tree/main/fonts][Nerd Fonts on GitHub]]
[[https://github.com/domtronn/all-the-icons.el/tree/master/fonts][All The Icons Fonts on GitHub]]

** Step 5 - How to Update (Emacs, Doom Emacs, Update Your Custom Config)

*** Emacs

- Uninstall the old Emacs, example ~Uninstall-30.2.exe~
- Then download the latest app
- Go to Control Panel -> User Accounts -> Change my environment variables.
  - Select =Path=, =Edit= and update your old path ~C:\Program Files\Emacs\(your-emacs-version)\bin~ folder and OK.

*** Doom Emacs Upgrade

Upgrading Doom Emacs updates the core Doom system, including its built-in packages and configuration framework. Running `doom upgrade` will:

- Pull the latest changes from Doom’s Git repository.
- Update all bundled packages to their newest versions.
- Fix any potential issues caused by outdated core files.

After upgrading, running `doom sync` ensures that all packages and your custom configurations are correctly applied. Restart Emacs to use the latest version.

- Open =git-bash.exe=

- Go to the Doom folder:

#+BEGIN_SRC bash
cd ~/.emacs.d/bin
#+END_SRC

- And run:

#+BEGIN_SRC bash
./doom upgrade
#+END_SRC

- Go again to:

#+BEGIN_SRC bash
cd ~/.emacs.d/bin
#+END_SRC

- Just in case, run:

#+BEGIN_SRC bash
./doom sync
#+END_SRC

*** Doom Emacs Update Your Custom Config

Updating Doom Emacs ensures that all your custom configurations, packages, and core files are synchronized with the latest changes. Running `doom sync` will:

- Install any new packages you added in your config.
- Remove packages you no longer use.
- Rebuild the autoloads to make your changes effective.
- Apply updates to Doom’s core files safely.

After running this command, restart Emacs to see your updated configuration in effect.

- Open =git-bash.exe=

- Type to go to the Doom folder:

#+BEGIN_SRC bash
cd ~/.emacs.d/bin
#+END_SRC

- And run:

#+BEGIN_SRC bash
./doom sync
#+END_SRC
