* Installing WSL2 in Windows 11

** Step 1 - Enable the Windows Subsystem for Linux

You must first enable the "Windows Subsystem for Linux" optional feature before installing any Linux distributions on Windows.

Open PowerShell as Administrator (Start menu > PowerShell > right-click > Run as Administrator) and enter this command:

#+BEGIN_SRC powershell
dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart
#+END_SRC

** Step 2 - Enable Virtual Machine feature
Before installing WSL 2, you must enable the Virtual Machine Platform optional feature.
Your machine will require virtualization capabilities to use this feature.

Open PowerShell as Administrator and run

#+BEGIN_SRC powershell
dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart
#+END_SRC

** Step 3 - Check what Wsl Version is

#+BEGIN_SRC powershell
wsl --status
#+END_SRC

if it shows:
Default Version: 2

then you can skip "Step 4"

** Step 4 - Set WSL2 as default

#+BEGIN_SRC powershell
wsl --set-default-version 2
#+END_SRC

** Step 5 - Update wsl

#+BEGIN_SRC powershell
wsl --update
#+END_SRC


** Step 6 - Installing Ubuntu 

Open Microsoft Store and search for ~Ubuntu~


* Installing Doom emacs


** Step 1 - Update Ubuntu and download other tools


#+BEGIN_SRC bash
sudo apt update && sudo apt upgrade --fix-missing
#+END_SRC


** Step 2 - Downloading Emacs and other tools.

#+BEGIN_SRC bash
sudo apt install emacs fd-find ripgrep markdown --fix-missing
#+END_SRC

** Step 3 - Clone Doom Emacs Files.

#+BEGIN_SRC bash
git clone --depth 1 https://github.com/doomemacs/doomemacs ~/.config/emacs
#+END_SRC

** Step 4 - Install Doom.

#+BEGIN_SRC bash
~/.config/emacs/bin/doom install
#+END_SRC

** Step 5 - Add Doom Emacs to PATH Make Doom commands like `doom sync` available from any directory.

#+BEGIN_SRC bash
echo 'export PATH="$HOME/.config/emacs/bin:$PATH"' >> ~/.bashrc
#+END_SRC

** Step 6 - Apply bashrc changes

#+BEGIN_SRC bash
source ~/.bashrc
#+END_SRC

** Step 7 - apply Doom config and update packages

#+BEGIN_SRC bash
doom sync
#+END_SRC

** Step 8 - check Doom Emacs setup for issues

#+BEGIN_SRC bash
doom doctor
#+END_SRC

** Step 9 - Create Symbolic Link For Doom Config

We need to sync Doom Emacs config files for other devices.

- First, we need to create the folder on our device if it doesn't exist yet.

#+BEGIN_SRC bash
mkdir -p /mnt/c/Syncthing/doom-emacs/
#+END_SRC

- Then, we need to move `~/.config/doom` to Windows Drive C.

#+BEGIN_SRC bash
mv ~/.config/doom /mnt/c/Syncthing/doom-emacs/
#+END_SRC

- Then, we remove the old `~/.config/doom` folder.

#+BEGIN_SRC bash
rm -rf ~/.config/doom
#+END_SRC

- Finally, we create the symbolic link.

#+BEGIN_SRC bash
ln -s /mnt/c/Syncthing/doom-emacs/doom ~/.config/doom
#+END_SRC

** Step 10 - Create Symbolic Link For My Vault

We need to sync my Vault files for other devices.

- First, we need to create the Vault folder on our device if it doesn't exist yet.

#+BEGIN_SRC bash
mkdir -p /mnt/c/Syncthing/doom-emacs/osama-vault
#+END_SRC

- Then, we create the symbolic link in WSL.

#+BEGIN_SRC bash
ln -s /mnt/c/Syncthing/doom-emacs/osama-vault ~/osama-vault
#+END_SRC

* Installting vcxsrv XLaunch Server

In Wsl2 wslg display server is built in but for doom emacs we need ~vcxsrv~ because its supports pasting long texts

** Step 1 - Download The App From GitHub

https://github.com/marchaesen/vcxsrv/releases

=vcxsrv-64.installer.exe=

** Step 2 - Installing it to Program Files

** Step 3 - Make it Launch With Doom emacss auto

Open Wsl Ubuntu and Paste this:

#+BEGIN_SRC bash
echo 'alias doomeamcs='\''pgrep -f vcxsrv.exe >/dev/null || "/mnt/c/Program Files/VcXsrv/vcxsrv.exe" :0 -multiwindow -clipboard -wgl -ac & export DISPLAY=$(ip route | awk "/^default/{print \$3}"):0.0 && setxkbmap -option ctrl:swapcaps && emacs & exit'\''' >> ~/.bashrc
#+END_SRC

** Step 7 - Apply bashrc changes

#+BEGIN_SRC bash
source ~/.bashrc
#+END_SRC

** Step 8 - Launching Doom Emacs + XLaunch with single command

#+BEGIN_SRC bash
doomemacs
#+END_SRC











sudo apt update && sudo apt upgrade -y

sudo apt install -y \
  autoconf automake autopoint bsd-mailx build-essential \
  dbus-x11 debhelper dpkg-dev g++-12 gawk gcc-12 git gvfs ibus-gtk3 \
  language-pack-en-base libacl1-dev libasound2-dev libaspell-dev \
  libatk1.0-dev libatk-bridge2.0-dev libatspi2.0-dev libcairo2-dev \
  libcanberra-gtk3-dev libdatrie-dev libdbus-1-dev libegl1 libenchant-2-dev \
  libflac-dev libfontconfig1-dev libfreetype6-dev libgif-dev libglib2.0-dev \
  libgnutls28-dev libgstreamer1.0-dev libgtk-3-dev libibus-1.0-dev \
  libjpeg-dev libjpeg8 liblcms2-dev liblockfile-dev libnotify-dev libpng-dev \
  libsasl2-dev libsecret-1-dev libselinux1-dev libsm-dev libsqlite3-dev \
  libssl-dev libtiff-dev libtree-sitter-dev libx11-dev libxpm-dev \
  libxml2-dev libxrender-dev libxslt1-dev libyaml-dev texinfo zlib1g-dev \
  libicu-dev libwebkit2gtk-4.0-dev libgdk-pixbuf2.0-0 libharfbuzz-dev \
  libgnomecanvas-2.0-0 libwayland-client0 libwayland-cursor0 \
  libwayland-egl1 libwayland-server0 \
  libncurses-dev libtinfo-dev libncurses5-dev libncursesw5-dev \
  libjansson-dev libmagickwand-dev libsystemd-dev libxft-dev \
  libgpm-dev libotf-dev libm17n-dev gnutls-bin ripgrep



اختيار نسخة محددة 
مثلًأ emacs-30

cd ~
git clone --depth 1 --branch emacs-30 https://github.com/emacs-mirror/emacs.git

or
اختيار اخر نسخة
git clone --depth 1 https://github.com/emacs-mirror/emacs.git


تأكد من ان اسم المجلد هو emacs in home folder


cd ~/emacs
export CC="gcc-12" CXX="gcc-12"
./autogen.sh
./configure --with-json --with-modules --with-native-compilation --with-pgtk
make -j$(nproc)
sudo make -j$(nproc) install











