* Doom Emacs Native in Windows

** Step 1 - Installing Important tools

*** Emacs App

doom emacs cant be used without emacs app so we need to download the installer from the website

[[https://www.gnu.org/software/emacs/download.html][GNU Emacs Offical Site]]

download it from ~nearby GNU mirror~
example: ~emacs-30.2-installer.exe ~

after that install it noramlly and make sure the installtion path is program files
example: ~C:\Program Files\Emacs~

*** Git Tool

We need git to download doom repo to our pc and we will use it for other emacs tools like magit

Download it from here:

[[https://git-scm.com/downloads/win][Git Offical Site]]

Standalone Installer:
~Git for Windows/x64 Setup.~

install it to ~C:\Tools~ and name it =Git=

*** fd Tool

we need ~fd~ because it can search by file name and its so fast

Download it from here:
[[https://github.com/sharkdp/fd/releases][fd releases on GitHub]]

make sure you download ~windows-gnu~

Extract Folder to ~C:\Tools~ and name it =fd=

*** ripgrep Tool

we need ~ripgrep~ because it can search texts in files which is pretty useful in somecases

Download it from here:

[[https://github.com/BurntSushi/ripgrep/releases][ripgrep releases on GitHub]]

make sure you download ~windows-gnu~

Extract Folder to ~C:\Tools~ and name it =ripgrep=


** Step 2 - Edit system environment variables

When we install tools like fd or ripgrep, Emacs (and Doom) needs to find them no matter where they are on the system.
By adding their installation folders to the system environment variables (PATH), we make these tools accessible from any terminal or program without typing the full path every time.


Go to Control panel -> User Accounts -> Change my environment variables.

New, type =HOME= and set your ~C:\Users\USERNAME~ and OK.  
Select =Path=, =edit= and add your ~C:\Program Files\Emacs\(your-emacs-version)\bin~ folder and OK.
Select =Path=, =edit= and add your ~C:\Tools\ripgrep~ folder and OK.  
Select =Path=, =edit= and add your ~C:\Tools\fd~ folder and OK.  
Click OK.

** Step 3 - Clone Doom repo

*** Open =git-bash.exe=

- Go to your home folder by typing:

#+BEGIN_SRC bash
cd ~
#+END_SRC

- Then clone the Doom repo:

#+BEGIN_SRC bash
git clone https://github.com/doomemacs/doomemacs ~/.emacs.d
#+END_SRC

- After the download is complete, type:

#+BEGIN_SRC bash
cd ~/.emacs.d/bin
#+END_SRC

- Then install Doom by typing:

#+BEGIN_SRC bash
./doom install
#+END_SRC

- If everything is fine, Doom is now installed.

- Go again to:

#+BEGIN_SRC bash
cd ~/.emacs.d/bin
#+END_SRC

- Just in case, run:

#+BEGIN_SRC bash
./doom sync
#+END_SRC

- Go to Control Panel -> User Accounts -> Change my environment variables.
  - Select =Path=, then =Edit= and add: ~C:\Users\USERNAME\.emacs.d\bin~, click OK -> OK.

*Now you can start emacs and will see the Doom dashboard!*


** Step 3 - How to Update (emacs, doomemacs, update you custom config)

*** Emacs

- uninstall the old emacs example ~Uninstall-30.2.exe~

- then download the lastest app for windows

- Go to Control Panel -> User Accounts -> Change my environment variables.
  - Select =Path=, =edit= and add your ~C:\Program Files\Emacs\(your-emacs-version)\bin~ folder and OK.

*** doom emacs update custom config

- Open =git-bash.exe=

- type to go the doom folder:

#+BEGIN_SRC bash
cd ~/.emacs.d/bin
#+END_SRC

- and run:

#+BEGIN_SRC bash
./doom sync
#+END_SRC

*** Doom emacs upgrade

- Open =git-bash.exe=

- go to the doom folder:

#+BEGIN_SRC bash
cd ~/.emacs.d/bin
#+END_SRC

- and run:

#+BEGIN_SRC bash
./doom upgrade
#+END_SRC

- Go again to:

#+BEGIN_SRC bash
cd ~/.emacs.d/bin
#+END_SRC

- Just in case, run:

#+BEGIN_SRC bash
./doom sync
#+END_SRC




