* Installing WSL2 in Windows 11

** Step 1 - Enable the Windows Subsystem for Linux

You must first enable the "Windows Subsystem for Linux" optional feature before installing any Linux distributions on Windows.

Open PowerShell as Administrator (Start menu > PowerShell > right-click > Run as Administrator) and enter this command:

#+BEGIN_SRC powershell
dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart
#+END_SRC

** Step 2 - Enable Virtual Machine feature
Before installing WSL 2, you must enable the Virtual Machine Platform optional feature.
Your machine will require virtualization capabilities to use this feature.

Open PowerShell as Administrator and run

#+BEGIN_SRC powershell
dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart
#+END_SRC

** Step 3 - Check what Wsl Version is

#+BEGIN_SRC powershell
wsl --status
#+END_SRC

if it shows:
Default Version: 2

then you can skip "Step 4"

** Step 4 - Set WSL2 as default

#+BEGIN_SRC powershell
wsl --set-default-version 2
#+END_SRC

** Step 5 - Update wsl

#+BEGIN_SRC powershell
wsl --update
#+END_SRC


** Step 6 - Installing Ubuntu 

Open Microsoft Store and search for ~Ubuntu~


* Installing Doom emacs


** Step 1 - Update Ubuntu and download other tools


#+BEGIN_SRC bash
sudo apt update && sudo apt upgrade --fix-missing
#+END_SRC


** Step 2 - Downloading Emacs and other tools.

#+BEGIN_SRC bash
sudo apt install emacs fd-find ripgrep markdown --fix-missing
#+END_SRC

** Step 3 - Clone Doom Emacs Files.

#+BEGIN_SRC bash
git clone --depth 1 https://github.com/doomemacs/doomemacs ~/.config/emacs
#+END_SRC

** Step 4 - Install Doom.

#+BEGIN_SRC bash
~/.config/emacs/bin/doom install
#+END_SRC

** Step 5 - Install Doom.

#+BEGIN_SRC bash
~/.config/emacs/bin/doom install
#+END_SRC

** Step 6 - Add Doom Emacs to PATH Make Doom commands like `doom sync` available from any directory.

#+BEGIN_SRC bash
echo 'export PATH="$HOME/.config/emacs/bin:$PATH"' >> ~/.bashrc
#+END_SRC


** Step 7 - Apply bashrc changes

#+BEGIN_SRC bash
source ~/.bashrc
#+END_SRC

** Step 8 - apply Doom config and update packages

#+BEGIN_SRC bash
doom sync
#+END_SRC

** Step 9 - check Doom Emacs setup for issues

#+BEGIN_SRC bash
doom doctor
#+END_SRC

** Step 10 - Create Symbolic Lin For Doom Config

We need to Sync Doom Emacs Config Files for other devices

- so first we need to move =~/.config/doom= to Windows Drive C

#+BEGIN_SRC bash
mv ~/.config/doom /mnt/c/Syncthing/emacs/DoomConfig
#+END_SRC

- Then we Remove The =~/.config/doom= folder 

#+BEGIN_SRC bash
rm -rf ~/.config/doom
#+END_SRC

- Last We Create Symbolic Link

#+BEGIN_SRC bash
ln -s /mnt/c/Syncthing/emacs/DoomConfig ~/.config/doom
#+END_SRC


* Installting vcxsrv XLaunch Server

In Wsl2 wslg display server is built in but for doom emacs we need ~vcxsrv~ because its supports pasting long texts

** Step 1 - Download The App From GitHub

https://github.com/marchaesen/vcxsrv/releases

=vcxsrv-64.installer.exe=

** Step 2 - Installing it to Program Files

** Step 3 - Make it Launch With Doom emacss auto

Open Wsl Ubuntu and Paste this:

#+BEGIN_SRC bash
echo 'alias doomeamcs='\''pgrep -f vcxsrv.exe >/dev/null || "/mnt/c/Program Files/VcXsrv/vcxsrv.exe" :0 -multiwindow -clipboard -wgl -ac & export DISPLAY=$(ip route | awk "/^default/{print \$3}"):0.0 && setxkbmap -option ctrl:swapcaps && emacs & exit'\''' >> ~/.bashrc
#+END_SRC

** Step 7 - Apply bashrc changes

#+BEGIN_SRC bash
source ~/.bashrc
#+END_SRC

** Step 8 - Launching Doom Emacs + XLaunch with single command

#+BEGIN_SRC bash
doomemacs
#+END_SRC




* Installing Syncthing To Sync Doom Config to Other Devices

** Step 1 - Installing Syncthing in Ubuntu

#+BEGIN_SRC bash
sudo apt install syncthing -y
#+END_SRC

** Step 2 - Open Syncthing

#+BEGIN_SRC bash
syncthing
#+END_SRC

** Step 3 - Add Doom Folder




